import Foundation

enum LocalizationStrings {
    static let ja: [String: String] = [
        // App
        "PennyLet": "PennyLet",
        "Track spending, reach goals": "支出を管理して目標を達成",
        "Sign In with Cloud": "クラウドでサインイン",
        "You'll be redirected to sign in securely.": "安全にサインインするためリダイレクトされます。",
        "Continue as Guest": "ゲストとして続ける",
        "Guest Mode": "ゲストモード",
        "Sign in to save your data and unlock all features.": "サインインしてデータを保存し、すべての機能を解放しましょう。",
        "Subscriptions": "サブスクリプション",
        "Active Subscriptions": "アクティブなサブスク",
        "found": "件見つかりました",
        "Yearly": "年間",
        "Detected on this device": "このデバイスで検出",
        "Expired": "期限切れ",
        "No App Store subscriptions found": "App Storeサブスクリプションが見つかりません",
        "Active subscriptions purchased through Apple will appear here automatically.": "Appleを通じて購入したアクティブなサブスクリプションが自動的に表示されます。",
        "Scan for Subscriptions": "サブスクリプションをスキャン",
        "PennyLet can detect your active App Store subscriptions and track them automatically.": "PennyLetはアクティブなApp Storeサブスクリプションを検出し、自動的に追跡します。",
        "Scan Now": "今すぐスキャン",
        "Scan Again": "再スキャン",
        "Scanning subscriptions...": "サブスクリプションをスキャン中...",
        "Checking active entitlements...": "有効な購入情報を確認中...",
        "Reviewing purchase history...": "購入履歴を確認中...",
        "Scanning transaction history...": "取引履歴を確認中...",
        "Subscription Tracker": "サブスクリプション管理",
        "Subscription": "サブスクリプション",
        "Subscription name": "サブスク名",
        "Add Subscription": "サブスクを追加",
        "Added": "追加済み",
        "New Subscription": "新しいサブスク",
        "Details": "詳細",
        "Billing": "請求",
        "Note": "メモ",
        "Optional note": "任意のメモ",
        "First charge": "初回支払い",
        "Save Subscription": "サブスクを保存",
        "Most common": "最も多い",
        "Track as subscription": "サブスクとして管理",
        "Future charges will be added automatically.": "次回以降の支払いを自動で追加します。",
        "Billing period": "請求周期",
        "Every 7 days": "7日ごと",
        "Every 14 days": "14日ごと",
        "2 weeks": "2週間",
        "Every 2 weeks": "2週間ごと",
        "Custom": "カスタム",
        "Custom renewal interval": "カスタム更新間隔",
        "Pick days": "日数を選択",
        "Every": "毎",
        "days": "日",
        "weeks": "週間",
        "months": "か月",
        "years": "年",
        "Next charge": "次回支払い",
        "tracked": "件を管理中",
        "App Store subscriptions": "App Storeのサブスク",
        "Manual subscriptions": "手動サブスク",
        "Suggested subscriptions": "候補のサブスク",
        "Suggested from transaction history": "取引履歴からの候補",
        "matches": "件一致",
        "Track subscriptions manually or scan eligible App Store purchases.": "手動でサブスクを管理するか、対象のApp Store購入をスキャンできます。",
        "For subscriptions outside the App Store, add them manually so PennyLet can renew them for you.": "App Store以外のサブスクは手動で追加すると、PennyLetが次回以降を自動で記録します。",
        "This checks App Store purchase history that iOS allows this app to access.": "このアプリにiOSが許可したApp Store購入情報だけを確認します。",
        "This scan only uses purchase information Apple makes available to this app.": "このスキャンではAppleがこのアプリに提供する購入情報だけを使用します。",
        "biweekly": "隔週",
        "Create Account or Sign In": "アカウント作成 / サインイン",
        "Account Required": "アカウントが必要です",
        "Upgrading to Pro requires an account. Create one or sign in to continue.": "Proへのアップグレードにはアカウントが必要です。アカウントを作成するかサインインしてください。",
        "Create Account": "アカウント作成",
        "Log In": "ログイン",

        // Onboarding
        "Already have an account? Log In": "アカウントをお持ちですか？ログイン",
        "Your data is stored locally on this device.": "データはこのデバイスにローカルに保存されます。",
        "Your financial data stays on this device.": "あなたの金融データはこの端末内に保存されます。",
        "No bank login required.": "銀行ログインは不要です。",
        "You can export or delete your data anytime.": "データはいつでもエクスポートまたは削除できます。",
        "Skip manual setup by importing a CSV file of your transactions.": "取引のCSVファイルをインポートして手動設定をスキップします。",
        "Start today. No bank import needed.": "今日から始められます。銀行データのインポートは不要です。",
        "Tell PennyLet what you have today and what is coming next. Past transactions are optional.": "今日持っているお金と次に入るお金を入力するだけで始められます。過去の取引は任意です。",
        "Make PennyLet yours": "PennyLetを自分らしく",
        "Choose the language and feel first. Then PennyLet will ask what you have today.": "まず言語と見た目を選びます。そのあと、今日持っているお金を入力します。",
        "Choose the app feel first. Then PennyLet will ask what you have today.": "まず見た目を選びます。そのあと、今日持っているお金を入力します。",
        "Already have a CSV? Import it optionally": "CSVがある場合だけ任意でインポート",
        "You can skip this. PennyLet works even without old bank data.": "ここはスキップできます。古い銀行データがなくてもPennyLetは使えます。",
        "What do you have today?": "今日いくら使えますか？",
        "Use the money picture you have right now. It does not need to match payday.": "今の状態を入力してください。給料日と一致していなくても大丈夫です。",
        "Spendable balance today": "今日使える残高",
        "Checking or usable balance": "普通預金など使える残高",
        "Money you can use before the next paycheck, for example your checking balance.": "次の給料日までに使えるお金。例：普通預金の残高。",
        "Cash in pocket": "手元の現金",
        "Physical cash you want PennyLet to count, for example 40.": "PennyLetに含めたい現金。例：40。",
        "Keep untouched": "触らず残すお金",
        "Emergency buffer or protected money": "緊急用や残しておきたいお金",
        "Money to protect from spending, for example an emergency buffer.": "使わず残したいお金。例：緊急用の余裕資金。",
        "PennyLet will start from these numbers and become useful immediately.": "PennyLetはこの数字から始めて、すぐに役立つように計算します。",
        "What is coming next?": "次に入るお金は？",
        "This bridges the gap between today and your next payday.": "今日から次の給料日までをつなぐための設定です。",
        "Normal monthly income": "通常の月収",
        "Your usual after-tax income for a full month, for example 5000.": "1か月分の通常の手取り収入。例：5000。",
        "Next paycheck amount": "次の給料額",
        "Defaults to monthly income": "未入力なら月収を使用",
        "What you expect on the next payday. Leave blank to use monthly income.": "次の給料日に入る予定額。空欄なら月収を使います。",
        "Next payday": "次の給料日",
        "Pay rhythm": "給料の周期",
        "Bills before payday": "給料日前に払う請求",
        "Rent, subscriptions, debt, etc.": "家賃、サブスク、借入など",
        "Bills due before the next paycheck, for example rent or subscriptions.": "次の給料日前に払う請求。例：家賃やサブスク。",
        "Save before payday": "給料日前に残す貯金",
        "Money you want to set aside before payday, for example 200.": "給料日前に取り分けたいお金。例：200。",
        "After this payday, PennyLet can continue with your normal monthly rhythm.": "この給料日以降は、通常の毎月のリズムで続けられます。",
        "Add a wallpaper now, or skip it and set one later in Settings.": "今壁紙を追加することも、あとで設定から追加することもできます。",
        "Start From Today": "今日から始める",
        "These fields power Safe Until Payday. They help PennyLet stay useful even when you start mid-month.": "これらの項目で「給料日まで使える金額」を計算します。月の途中から始めても役立ちます。",
        "Safe Until Payday": "給料日まで使える金額",
        "Daily until payday": "給料日までの1日あたり",
        "Based on money you have today.": "今日持っているお金をもとにしています。",
        "Next income": "次の収入",
        "on": "日付",
        "your next payday": "次の給料日",
        "Why this number?": "この数字の理由",
        "Money you have today": "今日あるお金",
        "Money counted today": "今日計算に入れるお金",
        "Bills still due": "まだ払う請求",
        "Known subscriptions": "把握済みのサブスク",
        "Subscriptions before payday": "給料日前のサブスク",
        "Savings to hold": "取り分ける貯金",
        "Protected money": "残しておくお金",
        "Not counted until payday.": "給料日までは計算に入れません。",
        "Next paycheck is for timing only.": "次の給料は日付の目安です。",
        "Safe until payday": "給料日まで使える金額",
        "Today Snapshot": "今日のスナップショット",
        "Update what you know today.": "今日わかっている内容を更新",
        "Update today's money.": "今日のお金を更新",
        "This keeps Safe Until Payday accurate without importing old bank data.": "古い銀行データを入れなくても、給料日まで使える金額を正確に保てます。",
        "No old bank history needed.": "古い銀行履歴は不要です。",
        "Preview": "プレビュー",
        "Data confidence": "データの確かさ",
        "Money check": "お金の確認",
        "Setup needed": "設定が必要です",
        "Add today's money picture so PennyLet can explain your safe amount.": "今日のお金の状態を入れると、使える金額を説明できます。",
        "Add what you have today so PennyLet can explain the number.": "今日あるお金を入れると、数字の理由がわかります。",
        "Needs review": "確認が必要",
        "Needs a quick check": "少し確認が必要",
        "Some entries need a quick check before reports are fully trusted.": "レポートを信頼する前に、いくつかの項目を確認してください。",
        "Review a few items so reports stay accurate.": "いくつか確認すると、レポートが正確になります。",
        "Strong local picture": "端末内の情報が十分です",
        "Clear local picture": "端末内の情報が明確です",
        "Based on your saved snapshot, reviewed entries, and upcoming commitments.": "保存したスナップショット、確認済みの記録、今後の支払いをもとにしています。",
        "Based on your saved snapshot and reviewed entries.": "保存したスナップショットと確認済みの記録をもとにしています。",
        "Based on today's snapshot": "今日のスナップショットが基準",
        "Useful now. It gets sharper as you add entries and subscriptions.": "今すぐ使えます。記録やサブスクを追加するとさらに正確になります。",
        "Useful now. Add entries when money moves.": "今すぐ使えます。お金が動いたら記録を追加してください。",
        "entries": "件",
        "Entries": "記録",
        "to review": "要確認",
        "upcoming": "予定",
        "Upcoming": "予定",
        "Review Queue": "確認キュー",
        "PennyLet asks before guessing.": "迷うときは勝手に決めません。",
        "Review": "確認",
        "Needs category": "カテゴリが必要",
        "Suggested category": "カテゴリ候補",
        "Possible transfer": "送金の可能性",
        "Possible credit card payment": "カード支払いの可能性",
        "Possible refund": "返金の可能性",
        "Possible reimbursement": "立替精算の可能性",
        "Possible recurring item": "定期項目の可能性",
        "Review recurring item": "定期項目を確認",
        "Possible Transfers": "送金の可能性",
        "Refunds & Reimbursements": "返金・立替精算",
        "Recurring Items": "定期項目",
        "Recurring item": "定期項目",
        "Confirm money you moved so it does not count as spending.": "移動したお金を確認すると、支出として数えません。",
        "Link money returned to the original purchase.": "戻ってきたお金を元の購入に紐づけます。",
        "Track repeated bills or subscriptions only after you confirm them.": "繰り返しの請求やサブスクは確認してから管理します。",
        "These entries need a category before reports are fully trusted.": "レポートを信頼する前に、カテゴリの確認が必要です。",
        "Same amount on nearby dates. Transfers are not counted as spending.": "近い日付に同額があります。送金は支出として数えません。",
        "This can reduce the original expense instead of inflating income.": "通常の収入として増やさず、元の支出を減らせます。",
        "Confirm before trusting this recurring item.": "信頼する前に、この定期項目を確認してください。",
        "Confirm before tracking.": "管理する前に確認してください。",
        "Accept Transfer": "送金として承認",
        "Accept Refund": "返金として承認",
        "Track Recurring": "定期項目として管理",
        "Ignore": "無視",
        "Show all": "すべて表示",
        "Show less": "少なく表示",
        "PennyLet will ask again when new local data needs a decision.": "新しいローカルデータに判断が必要なとき、PennyLetがまた確認します。",
        "Confirm only what makes sense. Ignore anything PennyLet should stop asking about.": "納得できるものだけ確認してください。不要な候補は無視できます。",
        "Check the few items PennyLet should not guess.": "PennyLetが勝手に決めない項目だけ確認します。",
        "Track the few things you care about.": "気になるものだけを見守ります。",
        "Watch a few spending habits.": "気になる支出を見守ります。",
        "Manage watchlists": "ウォッチリストを管理",
        "Choose coffee, dining, Amazon, games, or anything you want to watch.": "コーヒー、外食、Amazon、ゲームなど見守りたいものを選べます。",
        "Pick merchants or categories to keep an eye on.": "気になる店名やカテゴリを選べます。",
        "Choose what to watch.": "見守るものを選択",
        "Add a merchant or category like Coffee, Dining, Amazon, games, or transit.": "コーヒー、外食、Amazon、ゲーム、交通などの店名やカテゴリを追加できます。",
        "Track a merchant or category without building a full budget.": "細かい予算を作らず、店名やカテゴリを見守れます。",
        "Watchlist name": "ウォッチリスト名",
        "Saved watchlists": "保存済みウォッチリスト",
        "No custom watchlists yet.": "カスタムウォッチリストはまだありません。",
        "Delete watchlist?": "ウォッチリストを削除しますか？",
        "This removes it from Home. Your transactions stay saved.": "ホームから削除します。取引データは残ります。",
        "Nothing needs review right now.": "今は確認が必要な項目はありません。",
        "User confirmed": "ユーザー確認済み",
        "Rule match": "ルール一致",
        "High confidence": "高い確度",
        "Medium confidence": "中くらいの確度",
        "Low confidence": "低い確度",
        "Unknown confidence": "不明な確度",
        "Transaction": "取引",
        "Uncategorized": "未分類",
        "Customize": "カスタマイズ",
        "Money Setup": "お金の設定",
        "Budget & Payday": "予算と給料日",
        "Choose what appears in each tab.": "各タブに表示する内容を選びます。",
        "Wallpaper, colors, and card opacity.": "壁紙、色、カードの濃さを調整します。",
        "Color mode, font, and week start.": "カラーモード、フォント、週の開始日を設定します。",
        "Income, payday, and today snapshot.": "収入、給料日、今日のスナップショットを設定します。",
        "Income, payday, and today's money.": "収入、給料日、今日のお金を設定します。",
        "Customize goal deposit buttons.": "目標への入金ボタンをカスタマイズします。",
        "Language and currency.": "言語と通貨を設定します。",
        "Automatic AI schedules.": "自動AI分析の時間を設定します。",
        "Import, export, reset, and app version.": "インポート、エクスポート、リセット、アプリバージョン。",
        "Developer tools and Pro testing.": "開発者ツールとProテスト。",
        "Privacy policy and terms.": "プライバシーポリシーと利用規約。",
        "Bank/checking money available now.": "今使える銀行・普通預金のお金。",
        "Money in your bank/checking today.": "今日の銀行・普通預金のお金。",
        "Physical cash PennyLet should count.": "PennyLetに含める手元の現金。",
        "Cash you want PennyLet to count.": "PennyLetに含める現金。",
        "Money PennyLet should protect from spending.": "PennyLetが支出から守るお金。",
        "Savings or buffer money to protect.": "守りたい貯金や余裕資金。",
        "Bills due before your next paycheck.": "次の給料日前に支払う請求。",
        "Expected income on the next payday.": "次の給料日に入る予定額。",
        "Income expected on payday.": "給料日に入る予定額。",
        "Usual take-home pay each month.": "毎月の通常の手取り額。",
        "Rent, utilities, subscriptions, and must-pay costs.": "家賃、光熱費、サブスクなど必ず払う費用。",
        "Money to protect each month.": "毎月残しておくお金。",
        "Detected from local transactions": "ローカル取引から検出",
        "help_start_from_today": "古い銀行データは不要です。今あるお金と次に入るお金から始められます。",
        "semimonthly": "月2回",
        "How PennyLet Works": "PennyLetの使い方",
        "Help": "ヘルプ",
        "Done": "完了",
        "Quick answers": "クイック回答",
        "Tap a question to learn more. Start with Safe to Spend if you are new.": "知りたい項目をタップしてください。初めてなら「今日使える金額」から見るのがおすすめです。",
        "Tap a question to learn more. Start with Start From Today if you are new.": "初めてなら「今日から始める」から。",
        "Start here": "まずここから",
        "Money logic": "お金の考え方",
        "Tools": "ツール",
        "Personalization & privacy": "カスタマイズとプライバシー",
        "Tap to show answer": "タップして回答を表示",
        "Tap to hide answer": "タップして回答を閉じる",
        "help_balance": "今月のお金の出入りをすばやく確認できます。",
        "help_safe_daily": "請求、目標、予定支出を引いた残りです。",
        "How Safe to Spend is calculated": "使ってよい金額の計算方法",
        "help_safe_to_spend_logic": "毎月のお金から請求、目標、借入、予定支出を引きます。",
        "Transfers and credit cards": "送金とクレジットカード",
        "help_transfers_credit_cards": "口座間の移動やカード支払いは支出にしません。",
        "Refunds and reimbursements": "返金と立替精算",
        "help_refunds_reimbursements": "返金はできるだけ元の買い物から差し引きます。",
        "Review suggestions": "確認する候補",
        "help_review_suggestions": "迷う項目は勝手に決めず、確認に回します。",
        "Watchlists": "ウォッチリスト",
        "help_watchlists": "コーヒー、外食、Amazonなどを見守れます。",
        "help_categories": "今月どこに使ったかを確認できます。",
        "AI Analysis": "AI分析",
        "Savings goals": "貯金目標",
        "Local data only": "ローカルデータのみ",
        "help_goals": "目標の進み具合を見て、すぐ入金できます。",
        "help_ai": "短い支出メモを作ります。オンラインAIが遅いときは端末内の要約を使います。",
        "help_subscriptions": "手動追加、App Storeスキャン、候補確認ができます。",
        "help_wallpaper": "写真、色、見た目をプロファイルに保存できます。",
        "help_local_privacy": "銀行ログイン不要。データは端末内に残ります。",
        "Welcome to PennyLet": "PennyLetへようこそ",
        "Track your spending, build healthy budgets, and reach your financial goals.": "支出を管理し、健全な予算を立て、目標を達成しましょう。",
        "Back": "戻る",
        "Next": "次へ",
        "Get Started": "始める",
        "Please enter a valid monthly income": "有効な月収を入力してください",
        "Preferences": "設定",
        "Appearance": "デザイン",
        "Preset themes": "プリセットテーマ",
        "Custom color": "カスタムカラー",
        "Visible Blocks": "表示するブロック",
        "Reset Visible Blocks": "表示ブロックをリセット",
        "Color Mode": "カラーモード",
        "Font": "フォント",
        "Wallpaper Theme": "壁紙テーマ",
        "Wallpaper": "壁紙",
        "PennyLet reads the main colors from your wallpaper and tints the app automatically.": "壁紙の主な色を読み取り、アプリの色合いを自動で合わせます。",
        "Import Wallpaper": "壁紙を選択",
        "Change Wallpaper": "壁紙を変更",
        "Remove Wallpaper Theme": "壁紙テーマを削除",
        "Analyzing wallpaper colors...": "壁紙の色を解析中...",
        "Wallpaper colors active": "壁紙カラーが有効です",
        "Wallpaper color themes": "壁紙カラーテーマ",
        "Card box color themes": "カード色テーマ",
        "Use wallpaper colors": "壁紙カラーを使う",
        "Use accent color": "アクセントカラーを使う",
        "Use background color": "背景カラーを使う",
        "Delete Wallpaper Theme": "壁紙テーマを削除",
        "Delete Wallpaper Theme?": "壁紙テーマを削除しますか？",
        "Only this saved wallpaper theme will be deleted.": "この保存済み壁紙テーマだけが削除されます。",
        "Saved Wallpaper Profiles": "保存済みの壁紙プロファイル",
        "Save Profile": "プロファイルを保存",
        "Name Profile": "プロファイル名",
        "Profile name": "プロファイル名",
        "Save the current wallpaper, crop, and appearance settings as a profile.": "現在の壁紙、切り抜き、表示設定をプロファイルとして保存します。",
        "Profile saved": "プロファイルを保存しました",
        "Crop Current Wallpaper": "現在の壁紙をトリミング",
        "Crop Wallpaper": "壁紙をトリミング",
        "Use Crop": "この切り抜きを使用",
        "Pinch and drag to frame your wallpaper.": "ピンチとドラッグで壁紙の見え方を調整します。",
        "Wallpaper theme is active. Remove it to use manual colors.": "壁紙テーマが有効です。手動カラーを使うには削除してください。",
        "Wallpaper visibility": "壁紙の表示",
        "Wallpaper blur": "壁紙のぼかし",
        "Card opacity": "カードの濃さ",
        "Wallpaper frame": "壁紙の位置調整",
        "Zoom": "ズーム",
        "Horizontal frame": "左右の位置",
        "Vertical frame": "上下の位置",
        "Could not read that image. Try another wallpaper.": "画像を読み込めませんでした。別の壁紙を試してください。",
        "Region": "地域",
        "Currency": "通貨",
        "Your Budget": "あなたの予算",
        "After tax": "税引後",
        "Essential Bills": "固定費",
        "Rent, utilities, etc.": "家賃、光熱費など",
        "Savings Goal": "貯金目標",
        "Monthly target": "月間目標",
        "Pay Day": "給料日",
        "Monthly plan": "月の計画",
        "Monthly income": "月収",
        "Your usual take-home income for a full month.": "1か月分のいつもの手取り収入です。",
        "Fixed bills": "固定費",
        "Rent, utilities, subscriptions, and other must-pay costs.": "家賃、光熱費、サブスクなど必ず払う費用です。",
        "Money to save": "貯めるお金",
        "Amount you want PennyLet to protect each month.": "毎月使わずに守りたい金額です。",
        "Pay schedule": "給料の予定",
        "Payday": "給料日",
        "Choose the day of the month your pay usually arrives.": "通常の給料日を1〜31日から選びます。",
        "Choose payday": "給料日を選択",
        "Today snapshot": "今日の状況",
        "Start from today": "今日から始める",
        "Use today's balance": "今日の残高を使う",
        "Use this when you started mid-month. PennyLet only counts money you already have until payday.": "月の途中から始めたときに使います。給料日までは、今あるお金だけを数えます。",
        "Today's money": "今日使えるお金",
        "Money available right now before your next payday.": "次の給料日までに今使えるお金です。",
        "Cash": "現金",
        "Physical cash you want counted.": "財布などにある現金で、計算に入れたい分です。",
        "Savings or buffer money PennyLet should not treat as spendable.": "貯金や予備費など、使えるお金に入れたくない分です。",
        "Must-pay costs due before your next paycheck.": "次の給料日前に必ず払う費用です。",
        "Money you want protected before the next paycheck.": "次の給料日前に使わず守りたい金額です。",
        "Next paycheck": "次の給料",
        "Legal": "法的情報",

        // Dashboard
        "Hello, ": "こんにちは、",
        "Summary": "サマリー",
        "Favorites": "よく見る項目",
        "Edit": "編集",
        "Monthly Income": "月収",
        "Good morning, ": "おはようございます、",
        "Good evening, ": "こんばんは、",
        "there": "ゲスト",
        "Safe to Spend Today": "今日使える金額",
        "Safe to Spend": "使ってよい金額",
        "Daily safe amount": "1日の安全額",
        "After upcoming bills, goals, and planned set-asides.": "今後の請求、目標、計画済みの積立を差し引いた後です。",
        "Daily spending lane": "今日の支出ライン",
        "Spent": "支出",
        "Income": "収入",
        "Balance": "残高",
        "Top Categories": "カテゴリ別",
        "This month": "今月",
        "Monthly pulse": "今月の流れ",
        "Your monthly picture will appear here.": "今月のお金の流れがここに表示されます。",
        "On track": "順調",
        "Over budget": "予算超過",
        "No spending this month": "今月の支出はありません",
        "Recent Activity": "最近の取引",
        "View All": "すべて見る",
        "No transactions yet": "まだ取引がありません",
        "d left": "日残り",
        "% used": "%使用",
        "% of budget used": "予算の%使用",

        // Activity
        "Activity": "取引",
        "Search transactions": "取引を検索",
        "Filter": "フィルター",
        "Activity Summary": "取引の概要",
        "No Transactions": "取引なし",
        "No Results": "結果なし",
        "Warns you when you're nearing your monthly spending limit.": "月間の支出制限に近づいたときに警告します。",
        "Sends email alerts to the address below. Requires server setup.": "下記のアドレスにメールアラートを送信します。サーバー設定が必要です。",
        "Export CSV": "CSVエクスポート",
        "File name": "ファイル名",
        "Export": "エクスポート",
        "Auto Analysis Help": "自動分析ヘルプ",
        "Auto Analysis automatically generates daily, weekly, and monthly AI spending insights at your scheduled times. Enable it and set your preferred times below.": "自動分析はAIによる日次・週次・月次の支出インサイトを自動生成します。有効にして時間を設定してください。",
        "Export Successful": "エクスポート成功",
        "File saved as": "ファイル名：",
        "Export & Reset": "エクスポート & リセット",
        "Export CSV & Reset": "CSVをエクスポートしてリセット",
        "Reset Without Export": "エクスポートせずにリセット",
        "Save your data as CSV before resetting? All local data will be cleared.": "リセット前にデータをCSVとして保存しますか？すべてのローカルデータが消去されます。",
        "Import CSV": "CSVをインポート",
        "Import Successful": "インポート成功",
        "Import Failed": "インポート失敗",
        "Imported": "インポート完了：",
        "transactions successfully.": "件の取引を正常にインポートしました。",
        "OK": "OK",
        "The file could not be read. Check the format and try again.": "ファイルを読み取れませんでした。フォーマットを確認して再試行してください。",
        "Generate Test Data": "テストデータを生成",
        "Add your first transaction": "最初の取引を追加しましょう",
        "Try a different search": "別のキーワードで検索",

        // Goals
        "Goals": "目標",
        "No Goals Yet": "まだ目標がありません",
        "Set savings goals to track your progress": "貯金目標を設定して進捗を管理しましょう",
        "% complete": "%達成",
        "Goal Details": "目標詳細",
        "Name": "名前",
        "Target Amount": "目標金額",
        "Current Amount": "現在の金額",
        "Frequency": "頻度",
        "Weekly": "毎週",
        "Biweekly": "隔週",
        "Monthly": "毎月",
        "New Goal": "新しい目標",
        "Add Goal": "目標を追加",
        "Savings direction": "貯金の進み具合",
        "active goals": "進行中の目標",
        "goals": "目標",
        "Delete Goal?": "目標を削除しますか？",
        "This cannot be undone.": "この操作は取り消せません。",
        "Add money": "金額を追加",
        "Goal Quick Add": "目標のクイック追加",
        "Quick amount": "クイック金額",
        "Custom amount": "カスタム金額",
        "Goal completed!": "目標達成！",
        "is fully funded.": "の貯金が完了しました。",
        "Money cockpit": "お金のコックピット",
        "Subscriptions and budget checks live here.": "サブスクと予算チェックをここで確認できます。",
        "Safe today": "今日の安全額",
        "Tracked subs": "管理中のサブスク",
        "Track recurring charges and renewal dates.": "定期支払いと更新日を管理します。",
        "See pacing, category pressure, and monthly health.": "予算ペース、カテゴリ負担、月次の健全性を確認します。",

        // Budget Health
        "Budget Health": "予算の健全性",
        "Budget Overview": "予算の概要",
        "Monthly Disposable": "月間自由支出",
        "Spending by Category": "カテゴリ別支出",
        "No spending data this month": "今月の支出データがありません",
        "Income vs Spending": "収入 vs 支出",
        "Key numbers": "主要な数値",
        "Remaining": "残り",
        "Safe Daily": "安全な1日額",
        "Days Left": "残り日数",

        // Upgrade
        "PennyLet Pro": "PennyLet Pro",
        "Free": "無料",
        "Pro": "Pro",
        "Plan": "プラン",
        "Yearly (save 40%)": "年間（40%割引）",
        "Processing...": "処理中...",
        "Subscribe": "購読する",
        "Restore Purchases": "購入を復元",
        "More AI Analyses": "より多くのAI分析",
        "30 daily, 15 weekly, 10 monthly, and 3 forecasts every month": "毎月30回のデイリー、15回のウィークリー、10回のマンスリー、3回の予測",
        "Custom Categories": "カスタムカテゴリ",
        "Create your own spending and income categories": "自分だけの支出・収入カテゴリを作成",
        "Spending Forecasts": "支出予測",
        "AI predicts next month's spending based on your history": "過去のデータからAIが来月の支出を予測",
        "Schedule automatic daily, weekly, and monthly AI analysis": "毎日・毎週・毎月のAI分析を自動スケジュール",
        "Forecast": "予測",
        "Spending Forecast": "支出予測",
        "Other": "その他",
        "Weekly Trend": "週間トレンド",
        "Next Month": "来月",
        "Monthly Limit Reached": "月間制限に達しました",
        "Please wait until the first of next month for your usage to refresh.": "来月1日までお待ちください。",
        "Free Uses Exhausted": "無料利用回数を使い切りました",
        "Upgrade to PennyLet Pro for more analyses and unlimited access.": "PennyLet Proにアップグレードして、より多くの分析と無制限のアクセスを。",
        " free left of ": "回の無料利用が残っています（全",
        " uses this month": "回/月）",
        "See AI-predicted spending for next month based on your history.": "過去の履歴に基づいてAIが予測した来月の支出を表示します。",
        "New": "新規",
        "New Category": "新しいカテゴリ",
        "Add": "追加",
        "Balance adjustments fix your starting balance. They stay out of spending reports.": "残高調整は開始残高を直すための項目です。支出レポートには入りません。",
        "Ignore keeps the entry visible but leaves it out of budgets and reports.": "無視にすると項目は残りますが、予算とレポートには入りません。",
        "Reimbursement is money paid back to you. PennyLet uses it to lower the original cost when possible.": "立替精算は返してもらったお金です。可能な場合、元の支出を下げる形で扱います。",
        "/mo": "/月",
        "Upgrade": "アップグレード",
        "Get more AI analyses, visual charts, forecasts, and deeper spending insights.": "より多くのAI分析、ビジュアルチャート、予測、より深い支出インサイトを。",
        "Higher AI limits, forecasts, charts, and automation for heavier tracking.": "より多く記録する人向けに、AI上限・予測・チャート・自動分析を強化します。",
        "Higher AI limits": "AI上限アップ",
        "Forecasts": "予測",
        "Charts": "チャート",
        "Wallpaper themes": "壁紙テーマ",
        "Visible block controls": "表示ブロック設定",
        "Pro unlocks": "Proで使える機能",
        "Free vs Pro": "無料版とPro",
        "Included": "利用可",
        "Richer AI reports": "より詳しいAIレポート",
        "Extra anomaly checks and tailored tips in AI reports": "AIレポートに異常チェックと個別のヒントを追加",
        "Visual Pie Charts": "ビジュアル円グラフ",
        "Beautiful spending breakdown charts in weekly and monthly reports": "週次・月次レポートの美しい支出内訳グラフ",
        "Deeper Spending Insights": "より深い支出インサイト",
        "Detailed patterns, trends, and personalized recommendations": "詳細なパターン、トレンド、パーソナライズされた提案",
        "Just $3.33/month": "月々たった$3.33",
        "AI Spending Insights": "AI支出分析",
        "Daily, weekly, and monthly analysis": "日次・週次・月次の分析",
        "Receipt Scanner": "レシートスキャン",
        "Snap receipts to log expenses instantly": "レシートを撮影して即座に記録",
        "Custom Tags": "カスタムタグ",
        "Organize transactions your way": "取引を自由に整理",
        "Budget Alerts": "予算アラート",
        "Get notified when nearing limits": "予算が近づいたら通知",
        "Advanced Charts": "高度なグラフ",
        "Deeper insights into your spending": "支出をより深く分析",
        "Unable to load pricing. Please try again.": "価格を読み込めませんでした。再試行してください。",
        "No active subscription found.": "有効なサブスクリプションが見つかりません。",
        "Purchase restored! Pro features are now unlocked.": "購入が復元されました！Pro機能のロックが解除されました。",
        "Pro unlocked! Refreshing...": "Proのロック解除！更新中...",

        // Receipt Scanner
        "Scan Receipt": "レシートをスキャン",
        "Take Photo": "写真を撮る",
        "Use": "使用",
        "Take a photo of your receipt": "レシートを撮影してください",
        "We'll extract the merchant, amount, and category automatically.": "店名、金額、カテゴリを自動的に抽出します。",
        "Choose Photo": "写真を選択",
        "Extracted Details": "抽出された情報",
        "Review & Edit": "確認と編集",
        "Tap fields to correct": "タップして修正",
        "Item": "品目",
        "Price": "価格",
        "Total": "合計",
        "Merchant": "店名",
        "Could not load image.": "画像を読み込めませんでした。",
        "Could not prepare image.": "画像を準備できませんでした。",
        "Uploading receipt...": "レシートをアップロード中...",
        "Analyzing with AI...": "AIで分析中...",
        "No text found. Try a clearer photo.": "テキストが見つかりません。より鮮明な写真でお試しください。",
        "Extracting details...": "詳細を抽出中...",
        "Receipt scanning is currently unavailable. Please try again later.": "レシートスキャンは現在利用できません。後でもう一度お試しください。",
        "Could not parse receipt. Try again.": "レシートを解析できませんでした。再試行してください。",

        // Charts / AI
        "Category Breakdown": "カテゴリ別内訳",
        "Daily Spending": "1日の支出",
        "Analysis": "分析",
        "PennyLet Intelligence": "PennyLetインテリジェンス",
        "Practical reads on your spending rhythm.": "支出のリズムを実用的に読み解きます。",
        "AI History": "AI履歴",
        "Money Checks": "マネーチェック",
        "Pro learns your rhythm from saved PennyLet data.": "Proは保存済みのPennyLetデータからあなたのリズムを学びます。",
        "Run a quick check when you want a plain-language read.": "わかりやすく確認したいときに、すぐチェックできます。",
        "PennyLet is ready to learn": "PennyLetは学ぶ準備ができています",
        "Run a Money Check and Pro will reuse the useful notes across the app.": "マネーチェックを実行すると、Proが役立つメモをアプリ内で活かします。",
        "Your money math still stays deterministic.": "お金の計算はこれまで通り確定したロジックで行います。",
        "Ask PennyLet": "PennyLetに聞く",
        "Ask about saved spending, watchlists, subscriptions, or payday.": "保存済みの支出、ウォッチリスト、サブスク、給料日について聞けます。",
        "What changed this week?": "今週なにが変わった？",
        "Pro noticed this": "Proが気づいたこと",
        "Open Money Checks": "マネーチェックを開く",
        "Clear saved insights": "保存済みインサイトを消去",
        "Ask about safe spending, subscriptions, watchlists, or what changed.": "使ってよい金額、サブスク、ウォッチリスト、変化について聞けます。",
        "Ask PennyLet is included with Pro.": "PennyLetに聞く機能はProに含まれます。",
        "No upcoming subscriptions or bills are saved yet.": "今後のサブスクや請求はまだ保存されていません。",
        "in the last 7 days": "直近7日間",
        "today": "今日",
        "this month": "今月",
        "Learns your rhythm": "リズムを学習",
        "Checks before payday": "給料日前に確認",
        "Pro learns your rhythm": "Proがリズムを学習",
        "Saved Money Checks help PennyLet explain future changes": "保存したマネーチェックで、今後の変化を説明しやすくします",
        "Payday forecasts": "給料日前の予測",
        "Look ahead with saved PennyLet data, not bank login": "銀行ログインではなく保存済みデータで先を見ます",
        "Source-backed Money Checks": "根拠つきマネーチェック",
        "Every answer stays tied to saved PennyLet data": "回答は保存済みPennyLetデータに基づきます",
        "Saved insight memory": "保存済みインサイトメモリ",
        "Proactive insight cards": "先回りインサイトカード",
        "Richer Money Checks": "より深いマネーチェック",

        // Common labels and settings
        "Language": "言語",
        "Privacy Policy": "プライバシーポリシー",
        "Terms of Use (EULA)": "利用規約（EULA）",
        "Category": "カテゴリ",
        "Budget": "予算",
        "Rate": "レート",
        "Converting...": "換算中...",
        "Could not fetch exchange rate.": "為替レートを取得できませんでした。",
        "Refresh Exchange Rates": "為替レートを更新",
        "Exchange rates updated": "為替レートを更新しました",
        "Date,Type,Category,Amount,Note,Merchant,OriginalCurrency,OriginalAmount,ExchangeRate": "日付,種類,カテゴリ,金額,メモ,店舗,元の通貨,元の金額,為替レート",
        "Purchase pending approval.": "購入は承認待ちです。",
        "Save 40%": "40%お得",
        "mo": "月",
        "Renews": "更新",
        "monthly": "月額",
        "yearly": "年額",
        "weekly": "週額",
        "daily": "日額",
        "subscription": "サブスクリプション",
        "unknown": "不明",

        // AI progress
        "Generate Again": "もう一度生成",
        "Usage": "使用状況",
        "AI progress": "AIの進行状況",
        "Current status": "現在の状態",
        "Preparing daily insight": "今日の分析を準備中",
        "Building weekly recap": "週間レポートを作成中",
        "Creating monthly insight": "月間分析を作成中",
        "Forecasting spending": "支出を予測中",
        "Reading your spending data": "支出データを読み込み中",
        "Reading local spending data": "ローカルの支出データを読み込み中",
        "Preparing AI request": "AIリクエストを準備中",
        "Building local analysis": "端末内の分析を作成中",
        "AI request sent": "AIリクエスト送信済み",
        "Waiting for AI response": "AIの応答を待機中",
        "PennyLet waits briefly, then finishes with private local math if needed.": "少しだけ待ち、必要ならプライベートな端末内計算で仕上げます。",
        "Using local backup summary": "端末内の代替分析を使用中",
        "Finishing with a local summary": "端末内の分析で仕上げ中",
        "Your local spending summary is being turned into a readable result.": "端末内の支出要約を読みやすい結果に変換しています。",
        "AI response received": "AIの応答を受信済み",
        "AI request timed out. Please check your connection and try again.": "AIリクエストがタイムアウトしました。接続を確認してもう一度お試しください。",
        "AI timed out. Try again.": "AIがタイムアウトしました。もう一度お試しください。",
        "AI service is unavailable. Please try again.": "AIサービスを利用できません。もう一度お試しください。",
        "Saving result locally": "結果を端末に保存中",
        "Result ready": "結果の準備完了",
        "Gathering today's transactions": "今日の取引を確認中",
        "Gathering this week's activity": "今週の動きを確認中",
        "Gathering this month's activity": "今月の動きを確認中",
        "Gathering forecast inputs": "予測に使うデータを確認中",
        "Preparing the daily prompt": "今日の分析内容を整理中",
        "Preparing the weekly prompt": "週間レポートの内容を整理中",
        "Preparing the monthly prompt": "月間分析の内容を整理中",
        "Preparing the forecast prompt": "予測リクエストを整理中",
        "AI is writing your daily insight": "AIが今日の分析を書いています",
        "AI is writing your weekly recap": "AIが週間レポートを書いています",
        "AI is writing your monthly insight": "AIが月間分析を書いています",
        "AI is building your spending forecast": "AIが支出予測を作成しています",
        "Checking the daily result": "今日の分析結果を確認中",
        "Checking the weekly result": "週間レポートを確認中",
        "Checking the monthly result": "月間分析を確認中",
        "Checking the forecast result": "予測結果を確認中",
        "Saving your daily insight": "今日の分析を保存中",
        "Saving your weekly recap": "週間レポートを保存中",
        "Saving your monthly insight": "月間分析を保存中",
        "Saving your forecast": "予測を保存中",
        "Reviewing local transactions, budgets, goals, categories, and recent activity.": "端末内の取引、予算、目標、カテゴリ、最近の動きを確認しています。",
        "Turning the relevant spending evidence into a focused AI request.": "関連する支出データをAIに渡すための要点にまとめています。",
        "Waiting for the AI to return a structured answer. Forecasts can take a little longer.": "AIが構造化された回答を返すのを待っています。予測は少し時間がかかることがあります。",
        "The online AI is taking too long, so PennyLet is using your on-device spending logic instead.": "オンラインAIの応答が遅いため、PennyLetが端末内の支出ロジックで代わりに作成しています。",
        "Checking the returned text, numbers, and chart data before showing it.": "表示前に文章、金額、チャート用データを確認しています。",
        "Saving the result on this device so it appears in history.": "履歴に表示されるよう、この端末に結果を保存しています。",
        "Your analysis is ready to read.": "分析を読める状態になりました。",
        "Finding patterns and outliers": "傾向と例外を確認中",
        "Writing tailored advice": "あなた向けのアドバイスを作成中",
        "Finalizing your result": "結果を仕上げ中",
        "Almost done": "もうすぐ完了",
        "Still working": "処理中",
        "AI is checking the details": "AIが詳細を確認中",
        "Larger histories can take longer": "履歴が多い場合は時間がかかります",
        "About": "約",
        "left": "残り",

        // Help copy
        "This month's income minus expenses. Positive means you're in the green; negative means you're overspending.": "今月の収入から支出を引いた金額です。プラスなら余裕があり、マイナスなら使いすぎの状態です。",
        "(Monthly income − essentials − savings goal − already spent) ÷ days remaining. If you spend more than this per day, you'll run out before month-end.": "（月収 − 固定費 − 貯金目標 − 使用済み金額）÷ 残り日数で計算します。この金額を超えるペースで使うと、月末前に予算が足りなくなります。",
        "Your spending this month broken down by category. Instantly see where your money goes.": "今月の支出をカテゴリ別に表示します。お金の使い先をすぐに確認できます。",
        "AI analyzes your spending patterns and provides daily, weekly, and monthly insights. Free tier includes limited uses.": "AIが支出パターンを分析し、日次・週次・月次のインサイトを届けます。無料プランでは利用回数に上限があります。",
        "Auto-detects App Store subscriptions on this device and shows monthly and yearly totals.": "このデバイスのApp Storeサブスクリプションを検出し、月額・年額の合計を表示します。",

        // Categories
        "Food & Dining": "食事・外食",
        "Groceries": "食料品",
        "Transport": "交通",
        "Shopping": "買い物",
        "Entertainment": "エンタメ",
        "Health": "健康",
        "Bills & Utilities": "請求・公共料金",
        "Rent / Housing": "家賃・住まい",
        "Travel": "旅行",
        "Education": "教育",
        "Gifts": "ギフト",
        "Salary": "給与",
        "Freelance": "フリーランス",
        "Investment": "投資",
        "Gift": "ギフト",

        // Themes and display
        "Light": "ライト",
        "Dark": "ダーク",
        "System": "システム",
        "Sage": "セージ",
        "Ocean": "オーシャン",
        "Sunset": "サンセット",
        "Lavender": "ラベンダー",
        "Forest": "フォレスト",
        "Midnight": "ミッドナイト",
        "Coral": "コーラル",
        "Honey": "ハニー",
        "Plum": "プラム",
        "Mint": "ミント",
        "Sky": "スカイ",
        "Blush": "ブラッシュ",
        "Inter": "Inter",
        "Serif": "セリフ",
        "Rounded": "丸み",
        "Mono": "等幅",

        // Shortened product copy
        "Export or delete anytime.": "いつでもエクスポート・削除できます。",
        "Start with what you have now. Past data can wait.": "今あるお金から始めましょう。過去データはあとで大丈夫です。",
        "Tell PennyLet what you have now. It helps from here.": "今あるお金を入力すれば、PennyLetはそこから役立ちます。",
        "No bank login": "銀行ログイン不要",
        "No old cleanup": "過去データの整理不要",
        "Explainable local numbers": "説明できる端末内の数字",
        "Pick a look first. Money setup comes next.": "まず見た目を選びます。お金の設定は次です。",
        "Pick the basics now. You can customize wallpaper later.": "まず基本だけ選びます。壁紙はあとで調整できます。",
        "Wallpaper themes live in Settings, so setup stays quick.": "壁紙テーマは設定で変更できます。セットアップは短く進めましょう。",
        "Have a CSV? Import it.": "CSVがあればインポート",
        "Optional. You can start without old data.": "任意です。古いデータなしで始められます。",
        "Use what you have right now. Payday does not need to match.": "今あるお金で大丈夫です。給料日と一致しなくてもOK。",
        "Money you can use before payday, like checking.": "給料日まで使えるお金。例：普通預金。",
        "Money you do not want to spend.": "使わず残したいお金。",
        "PennyLet starts from today.": "PennyLetは今日から始められます。",
        "This connects today to payday.": "今日から給料日までをつなぎます。",
        "Your usual take-home for a full month.": "1か月分の手取り収入。",
        "Leave blank to use monthly income.": "空欄なら月収を使います。",
        "Bills due before payday, like rent or subscriptions.": "給料日前の請求。例：家賃やサブスク。",
        "Money to set aside before payday.": "給料日前に取り分けるお金。",
        "After payday, PennyLet uses your normal rhythm.": "給料日後は通常のリズムで続きます。",
        "Add a wallpaper now, or do it later.": "壁紙は今でもあとでも追加できます。",
        "Save this wallpaper as a profile.": "この壁紙をプロファイルとして保存します。",
        "New here? Start with Start From Today.": "初めてなら「今日から始める」から。",
        "Start with what you have. PennyLet explains what is safe.": "今あるお金から始めましょう。PennyLetが使える金額を説明します。",
        "No old history required": "過去の履歴は不要",
        "help_no_old_history": "PennyLetは今日の状態だけで役立ちます。CSVインポートは任意で、必須ではありません。",
        "What AI can use": "AIが使うデータ",
        "help_ai_scope": "AIには、PennyLetが保存済みデータから作った要約だけを渡します。オンラインAIが遅いときは端末内の計算で表示します。",
        "When data is missing": "データが足りないとき",
        "help_data_gaps": "PennyLetは足りない履歴をあるように見せません。保存されているデータをもとに答えます。",
        "Ready from today": "今日から使えます",
        "Add your first entry when money moves. Past bank history can wait.": "お金が動いたら最初の記録を追加しましょう。過去の銀行履歴は後で大丈夫です。",
        "Old data optional": "過去データは任意",
        "Local first": "ローカル優先",
        "Export a CSV first? Reset clears local data.": "先にCSVを書き出しますか？リセットで端末内データは消えます。",
        "PennyLet pulls colors from your wallpaper.": "壁紙から色を取り込みます。",
        "Helps PennyLet stay useful when you start mid-month.": "月の途中からでも使いやすくします。",
        "Private logic for transfers, refunds, recurrings, and reviews.": "送金、返金、定期支払い、確認候補を端末内で処理します。",
        "Auto Analysis runs at the times you choose.": "自動分析は選んだ時間に実行します。",
        "Pinch and drag to frame it.": "ピンチとドラッグで位置調整。",
        "Checking App Store purchase info iOS allows.": "iOSが許可する購入情報を確認中。",
        "Apple subscriptions appear here.": "Appleのサブスクがここに表示されます。",
        "Add non-App Store subscriptions manually.": "App Store以外は手動で追加。",
        "PennyLet can scan eligible App Store subscriptions.": "対象のApp Storeサブスクをスキャンできます。",
        "Uses only purchase info Apple shares with this app.": "Appleがこのアプリに共有する購入情報だけを使います。",
        "Create an account to unlock Pro. Your local setup stays yours.": "アカウントを作るとProを解除できます。ローカル設定はそのままです。",
        "Your usage refreshes next month.": "利用回数は来月リセットされます。",
        "Upgrade for more AI analyses.": "アップグレードでAI分析を増やせます。",
        "Cash you physically have, like money in your wallet.": "財布などにある現金。",
        "Money to protect, like emergency savings.": "緊急用など、使わず守るお金。",
        "Needs attention": "確認が必要",
        "Ready": "準備OK",
        "Update your balance when money changes.": "お金が動いたら残高を更新しましょう。",
        "Updated today": "今日更新",
        "Updated": "更新日",
        "Today's money − protected money − bills before payday.": "今日のお金 − 残しておくお金 − 給料日前の請求。",
        "Days left": "残り日数",
        "Quick amounts": "クイック金額",
        "Quick checks": "クイック確認",
        "Confirm only what looks right. Ignore the rest.": "正しいものだけ確認。不要なものは無視できます。",
        "Check now": "今すぐ確認",
        "Track one habit without building a full budget.": "細かい予算なしで、気になる支出を1つ見守れます。",
        "Games": "ゲーム",
        "Start with one thing": "まず1つ選ぶ",
        "Set the four amounts that appear on goal cards.": "目標カードに表示する4つの金額を設定します。",
        "More private reports": "プライベートレポートを増やす",
        "Auto check-ins": "自動チェック",
        "More daily, weekly, monthly, and forecast runs": "日次・週次・月次・予測をもっと使えます",
        "Forecasts from your history": "履歴から予測",
        "Forecasts from your saved history": "保存した履歴から予測します",
        "Always included": "いつでも含まれる機能",
        "PennyLet never asks for bank credentials.": "PennyLetが銀行の認証情報を求めることはありません。",
        "Old transactions are optional. Today's snapshot is enough to begin.": "過去の取引は任意です。今日の状態だけで始められます。",
        "Explainable numbers": "説明できる数字",
        "Safe to Spend is based on saved local data, bills, goals, and set-asides.": "使える金額は、保存済みの端末内データ、請求、目標、取り分け額から計算されます。",
        "Source-backed reports": "根拠のあるレポート",
        "Source-backed AI checks": "根拠つきAIチェック",
        "Reports stay tied to saved PennyLet data": "レポートは保存済みのPennyLetデータに基づきます",
        "Local fallback reports": "端末内バックアップレポート",
        "A local summary appears if online AI is slow": "オンラインAIが遅い場合は端末内要約を表示します",
        "Clear weekly and monthly charts": "週次・月次チャート",
        "Clear weekly and monthly category charts": "週次・月次のカテゴリチャート",
        "Your own categories": "自分のカテゴリ",
        "Create categories that match your life": "自分の生活に合うカテゴリを作れます",
        "Scheduled AI check-ins": "予約AIチェック",
        "Scheduled check-ins without opening the app": "アプリを開かなくても定期チェック",
        "Smarter checks and tips": "より賢い確認とヒント",
        "Reading your local money data.": "端末内データを確認中。",
        "Preparing the AI request.": "AIリクエストを準備中。",
        "Waiting for AI. Forecasts can take longer.": "AIの応答待ち。予測は少し長めです。",
        "Waiting briefly for online AI. PennyLet will switch to local math if it takes too long.": "オンラインAIを少し待っています。時間がかかる場合は端末内計算に切り替えます。",
        "AI is slow, so PennyLet is using a local summary.": "AIが遅いため、端末内の要約を使います。",
        "Checking the result.": "結果を確認中。",
        "Saving on this device.": "端末に保存中。",
        "Appearance & Wallpaper": "外観と壁紙",
        "Theme, wallpaper, colors, and card opacity.": "テーマ、壁紙、色、カードの濃さを設定します。",
        "Drag to reorder. Tap plus or check to show or hide.": "並べ替えはドラッグ。＋またはチェックで表示を切り替えます。",
        "Reset Home Layout": "ホーム配置をリセット",
        "Hide": "非表示",
        "Show": "表示",
        "Preparing export...": "エクスポートを準備中...",
        "Preparing your CSV.": "CSVを作成しています。",
        "Delete subscription?": "サブスクを削除しますか？",
        "Goal deposit shortcut": "目標に入金するショートカット",
        "Track spending you care about.": "気になる支出を見守ります。",
        "Watchlists track spending for a merchant or category you care about, like coffee, dining, Amazon, games, or transit.": "ウォッチリストは、コーヒー、外食、Amazon、ゲーム、交通など、気になる店名やカテゴリの支出を追跡します。",
        "Money you can use after bills, goals, and planned costs.": "請求、目標、予定支出を引いたあとに使えるお金です。",
        "Money in − money out this month. A quick pulse check.": "今月のお金の入り − 出たお金。かんたんな確認です。",
        "Money you have − bills − goals − known costs.": "今あるお金 − 請求 − 目標 − わかっている支出。",

        // Misc
        "Developer Mode": "開発者モード",
        "Type": "種類",
        "All": "すべて",
        "Expense": "支出",
        "Save": "保存",
        "Cancel": "キャンセル",
        "Delete": "削除",
        "Theme": "テーマ",
        "Saving...": "保存中...",
    ]

    static let zh: [String: String] = [
        // App
        "PennyLet": "PennyLet",
        "Track spending, reach goals": "追踪支出，实现目标",
        "Sign In with Cloud": "通过云端登录",
        "You'll be redirected to sign in securely.": "您将被重定向以安全登录。",
        "Continue as Guest": "以游客身份继续",
        "Guest Mode": "游客模式",
        "Sign in to save your data and unlock all features.": "登录以保存数据并解锁所有功能。",
        "Subscriptions": "订阅",
        "Active Subscriptions": "活跃订阅",
        "found": "个",
        "Yearly": "每年",
        "Detected on this device": "在此设备上检测到",
        "Expired": "已过期",
        "No App Store subscriptions found": "未找到App Store订阅",
        "Active subscriptions purchased through Apple will appear here automatically.": "通过Apple购买的活跃订阅将自动显示在这里。",
        "Scan for Subscriptions": "扫描订阅",
        "PennyLet can detect your active App Store subscriptions and track them automatically.": "PennyLet可以检测您活跃的App Store订阅并自动追踪。",
        "Scan Now": "立即扫描",
        "Scan Again": "重新扫描",
        "Scanning subscriptions...": "正在扫描订阅...",
        "Checking active entitlements...": "正在检查有效购买信息...",
        "Reviewing purchase history...": "正在查看购买历史...",
        "Scanning transaction history...": "正在分析交易记录...",
        "Subscription Tracker": "订阅追踪",
        "Subscription": "订阅",
        "Subscription name": "订阅名称",
        "Add Subscription": "添加订阅",
        "Added": "已添加",
        "New Subscription": "新建订阅",
        "Details": "详情",
        "Billing": "扣款",
        "Note": "备注",
        "Optional note": "可选备注",
        "First charge": "首次扣款",
        "Save Subscription": "保存订阅",
        "Most common": "最常见",
        "Track as subscription": "作为订阅追踪",
        "Future charges will be added automatically.": "之后的扣款会自动添加到记录中。",
        "Billing period": "扣款周期",
        "Every 7 days": "每7天",
        "Every 14 days": "每14天",
        "2 weeks": "2周",
        "Every 2 weeks": "每两周",
        "Custom": "自定义",
        "Custom renewal interval": "自定义续费间隔",
        "Pick days": "选择天数",
        "Every": "每",
        "days": "天",
        "weeks": "周",
        "months": "个月",
        "years": "年",
        "Next charge": "下次扣款",
        "tracked": "个已追踪",
        "App Store subscriptions": "App Store 订阅",
        "Manual subscriptions": "手动订阅",
        "Suggested subscriptions": "可能的订阅",
        "Suggested from transaction history": "根据交易记录推测",
        "matches": "次匹配",
        "Track subscriptions manually or scan eligible App Store purchases.": "手动管理订阅，或扫描可用的 App Store 购买记录。",
        "For subscriptions outside the App Store, add them manually so PennyLet can renew them for you.": "App Store 之外的订阅可以手动添加，之后 PennyLet 会自动记录续费。",
        "This checks App Store purchase history that iOS allows this app to access.": "这里只会检查 iOS 允许本应用访问的 App Store 购买信息。",
        "This scan only uses purchase information Apple makes available to this app.": "此扫描仅使用 Apple 提供给本应用的购买信息。",
        "biweekly": "每两周",
        "Create Account or Sign In": "创建账户 / 登录",
        "Account Required": "需要账户",
        "Upgrading to Pro requires an account. Create one or sign in to continue.": "升级到Pro需要账户。请创建账户或登录以继续。",
        "Create Account": "创建账户",
        "Log In": "登录",

        // Onboarding
        "Already have an account? Log In": "已有账户？登录",
        "Your data is stored locally on this device.": "您的数据本地存储在此设备上。",
        "Your financial data stays on this device.": "您的财务数据会留在这台设备上。",
        "No bank login required.": "不需要登录银行账户。",
        "You can export or delete your data anytime.": "您可以随时导出或删除数据。",
        "Skip manual setup by importing a CSV file of your transactions.": "通过导入交易CSV文件跳过手动设置。",
        "Start today. No bank import needed.": "从今天开始，不需要导入银行数据。",
        "Tell PennyLet what you have today and what is coming next. Past transactions are optional.": "告诉 PennyLet 您现在有多少钱、接下来会收到什么钱。过去交易可以不导入。",
        "Make PennyLet yours": "先设置您的 PennyLet",
        "Choose the language and feel first. Then PennyLet will ask what you have today.": "先选择语言和外观，然后 PennyLet 会询问您今天手上有多少钱。",
        "Choose the app feel first. Then PennyLet will ask what you have today.": "先选择应用外观，然后 PennyLet 会询问您今天手上有多少钱。",
        "Already have a CSV? Import it optionally": "已经有 CSV？可选择导入",
        "You can skip this. PennyLet works even without old bank data.": "这一步可以跳过。没有旧银行数据也能使用 PennyLet。",
        "What do you have today?": "今天手上有多少钱？",
        "Use the money picture you have right now. It does not need to match payday.": "填写现在真实的资金情况，不需要刚好是发薪日。",
        "Spendable balance today": "今天可用余额",
        "Checking or usable balance": "银行卡或可用余额",
        "Money you can use before the next paycheck, for example your checking balance.": "下次发薪前可以使用的钱，例如银行卡可用余额。",
        "Cash in pocket": "手头现金",
        "Physical cash you want PennyLet to count, for example 40.": "希望 PennyLet 计入的现金，例如 40。",
        "Keep untouched": "不要动用的钱",
        "Emergency buffer or protected money": "应急金或想保留的钱",
        "Money to protect from spending, for example an emergency buffer.": "想保护不花的钱，例如应急金。",
        "PennyLet will start from these numbers and become useful immediately.": "PennyLet 会从这些数字开始，马上给出有用结果。",
        "What is coming next?": "接下来会收到什么？",
        "This bridges the gap between today and your next payday.": "这会帮助 PennyLet 连接今天到下次发薪日之间的空档。",
        "Normal monthly income": "正常月收入",
        "Your usual after-tax income for a full month, for example 5000.": "一个完整月份通常的税后收入，例如 5000。",
        "Next paycheck amount": "下次工资金额",
        "Defaults to monthly income": "不填则使用月收入",
        "What you expect on the next payday. Leave blank to use monthly income.": "下次发薪日预计收到的金额。留空则使用月收入。",
        "Next payday": "下次发薪日",
        "Pay rhythm": "发薪周期",
        "Bills before payday": "发薪日前要付的账单",
        "Rent, subscriptions, debt, etc.": "房租、订阅、债务等",
        "Bills due before the next paycheck, for example rent or subscriptions.": "下次发薪前要支付的账单，例如房租或订阅。",
        "Save before payday": "发薪日前要留存的储蓄",
        "Money you want to set aside before payday, for example 200.": "发薪前想先留出来的钱，例如 200。",
        "After this payday, PennyLet can continue with your normal monthly rhythm.": "这次发薪日之后，PennyLet 可以继续按您的正常月度节奏运行。",
        "Add a wallpaper now, or skip it and set one later in Settings.": "可以现在添加壁纸，也可以跳过后在设置里添加。",
        "Start From Today": "从今天开始",
        "These fields power Safe Until Payday. They help PennyLet stay useful even when you start mid-month.": "这些项目会用于计算“发薪日前可用金额”，即使月中开始也能有用。",
        "Safe Until Payday": "发薪日前可用金额",
        "Daily until payday": "发薪日前每日可用",
        "Based on money you have today.": "基于今天手上已有的钱。",
        "Next income": "下次收入",
        "on": "日期",
        "your next payday": "下次发薪日",
        "Why this number?": "这个数字怎么算来？",
        "Money you have today": "今天已有的钱",
        "Money counted today": "今天计入的钱",
        "Bills still due": "还要支付的账单",
        "Known subscriptions": "已知订阅",
        "Subscriptions before payday": "发薪日前的订阅",
        "Savings to hold": "要留出的储蓄",
        "Protected money": "要保护的钱",
        "Not counted until payday.": "发薪日前不会计入可花金额。",
        "Next paycheck is for timing only.": "下次工资只用于确认时间。",
        "Safe until payday": "发薪日前可用金额",
        "Today Snapshot": "今日资金快照",
        "Update what you know today.": "更新今天已知的信息",
        "Update today's money.": "更新今天的钱",
        "This keeps Safe Until Payday accurate without importing old bank data.": "不用导入旧银行数据，也能让发薪日前可用金额保持准确。",
        "No old bank history needed.": "不需要旧银行记录。",
        "Preview": "预览",
        "Data confidence": "数据可信度",
        "Money check": "资金检查",
        "Setup needed": "需要设置",
        "Add today's money picture so PennyLet can explain your safe amount.": "填写今天的资金情况后，PennyLet 才能解释可用金额。",
        "Add what you have today so PennyLet can explain the number.": "填写今天已有的钱，PennyLet 才能解释这个数字。",
        "Needs review": "需要确认",
        "Needs a quick check": "需要快速确认",
        "Some entries need a quick check before reports are fully trusted.": "有些项目需要快速确认后，报表才更可靠。",
        "Review a few items so reports stay accurate.": "确认几项内容后，报表会更准确。",
        "Strong local picture": "本机数据较完整",
        "Clear local picture": "本机数据较清楚",
        "Based on your saved snapshot, reviewed entries, and upcoming commitments.": "基于已保存的快照、已确认记录和即将到来的支出。",
        "Based on your saved snapshot and reviewed entries.": "基于已保存的快照和已确认记录。",
        "Based on today's snapshot": "基于今日资金快照",
        "Useful now. It gets sharper as you add entries and subscriptions.": "现在就能用。添加交易和订阅后会更准确。",
        "Useful now. Add entries when money moves.": "现在就能用。钱有变化时再添加记录。",
        "entries": "项",
        "Entries": "记录",
        "to review": "待确认",
        "upcoming": "即将发生",
        "Upcoming": "即将发生",
        "Review Queue": "待确认队列",
        "PennyLet asks before guessing.": "不确定时，PennyLet 会先询问。",
        "Review": "确认",
        "Needs category": "需要分类",
        "Suggested category": "建议分类",
        "Possible transfer": "可能是转账",
        "Possible credit card payment": "可能是信用卡还款",
        "Possible refund": "可能是退款",
        "Possible reimbursement": "可能是报销",
        "Possible recurring item": "可能是定期项目",
        "Review recurring item": "确认定期项目",
        "Possible Transfers": "可能的转账",
        "Refunds & Reimbursements": "退款与报销",
        "Recurring Items": "定期项目",
        "Recurring item": "定期项目",
        "Confirm money you moved so it does not count as spending.": "确认转账后，这些金额不会算作支出。",
        "Link money returned to the original purchase.": "把退回的钱关联到原购买。",
        "Track repeated bills or subscriptions only after you confirm them.": "只有在您确认后，才会追踪重复账单或订阅。",
        "These entries need a category before reports are fully trusted.": "这些项目需要分类后，报表才更可靠。",
        "Same amount on nearby dates. Transfers are not counted as spending.": "附近日期有相同金额。转账不会算作支出。",
        "This can reduce the original expense instead of inflating income.": "这可以抵扣原支出，而不是虚增收入。",
        "Confirm before trusting this recurring item.": "请先确认此定期项目，再将其视为可信。",
        "Confirm before tracking.": "确认后再追踪。",
        "Accept Transfer": "确认为转账",
        "Accept Refund": "确认为退款",
        "Track Recurring": "追踪定期项目",
        "Ignore": "忽略",
        "Show all": "显示全部",
        "Show less": "收起",
        "PennyLet will ask again when new local data needs a decision.": "当新的本机数据需要判断时，PennyLet 会再次询问。",
        "Confirm only what makes sense. Ignore anything PennyLet should stop asking about.": "只确认合理的项目。不想再看到的建议可以忽略。",
        "Check the few items PennyLet should not guess.": "只确认 PennyLet 不该擅自判断的项目。",
        "Track the few things you care about.": "只关注您在意的几件事。",
        "Watch a few spending habits.": "关注几个重要的消费习惯。",
        "Manage watchlists": "管理关注列表",
        "Choose coffee, dining, Amazon, games, or anything you want to watch.": "可关注咖啡、外食、Amazon、游戏等项目。",
        "Pick merchants or categories to keep an eye on.": "选择想关注的商家或分类。",
        "Choose what to watch.": "选择要关注的项目",
        "Add a merchant or category like Coffee, Dining, Amazon, games, or transit.": "添加商家或分类，例如咖啡、外食、Amazon、游戏或交通。",
        "Track a merchant or category without building a full budget.": "不用建立完整预算，也能关注商家或分类。",
        "Watchlist name": "关注名称",
        "Saved watchlists": "已保存关注列表",
        "No custom watchlists yet.": "还没有自定义关注列表。",
        "Delete watchlist?": "删除关注列表？",
        "This removes it from Home. Your transactions stay saved.": "这只会从首页移除，交易记录仍会保留。",
        "Nothing needs review right now.": "目前没有需要确认的项目。",
        "User confirmed": "用户已确认",
        "Rule match": "规则匹配",
        "High confidence": "高可信度",
        "Medium confidence": "中等可信度",
        "Low confidence": "低可信度",
        "Unknown confidence": "未知可信度",
        "Transaction": "交易",
        "Uncategorized": "未分类",
        "Customize": "自定义",
        "Money Setup": "资金设置",
        "Budget & Payday": "预算和发薪日",
        "Choose what appears in each tab.": "选择每个标签页显示哪些内容。",
        "Wallpaper, colors, and card opacity.": "设置壁纸、颜色和卡片不透明度。",
        "Color mode, font, and week start.": "设置颜色模式、字体和每周开始日。",
        "Income, payday, and today snapshot.": "设置收入、发薪日和今日资金快照。",
        "Income, payday, and today's money.": "设置收入、发薪日和今天的钱。",
        "Customize goal deposit buttons.": "自定义目标存钱按钮。",
        "Language and currency.": "设置语言和货币。",
        "Automatic AI schedules.": "设置自动 AI 分析时间。",
        "Import, export, reset, and app version.": "导入、导出、重置和应用版本。",
        "Developer tools and Pro testing.": "开发者工具和 Pro 测试。",
        "Privacy policy and terms.": "隐私政策和条款。",
        "Bank/checking money available now.": "现在可用的银行或活期账户余额。",
        "Money in your bank/checking today.": "今天银行或活期账户里的钱。",
        "Physical cash PennyLet should count.": "希望 PennyLet 计入的现金。",
        "Cash you want PennyLet to count.": "希望 PennyLet 计入的现金。",
        "Money PennyLet should protect from spending.": "希望 PennyLet 保护、不用于消费的钱。",
        "Savings or buffer money to protect.": "想保护的储蓄或缓冲金。",
        "Bills due before your next paycheck.": "下次发薪前需要支付的账单。",
        "Expected income on the next payday.": "下次发薪日预计收到的收入。",
        "Income expected on payday.": "发薪日预计收到的收入。",
        "Usual take-home pay each month.": "每月通常到手收入。",
        "Rent, utilities, subscriptions, and must-pay costs.": "房租、水电、订阅等必须支付的费用。",
        "Money to protect each month.": "每月想保护起来的钱。",
        "Detected from local transactions": "根据本机交易检测",
        "help_start_from_today": "不需要旧银行数据。PennyLet 会从您现在有的钱和接下来会收到的钱开始。",
        "semimonthly": "每月两次",
        "How PennyLet Works": "PennyLet使用指南",
        "Help": "帮助",
        "Done": "完成",
        "Quick answers": "快速解答",
        "Tap a question to learn more. Start with Safe to Spend if you are new.": "点开问题就能查看说明。如果刚开始使用，建议先看“今日可安全支出”。",
        "Tap a question to learn more. Start with Start From Today if you are new.": "点开问题就能查看说明。如果刚开始使用，建议先看“从今天开始”。",
        "Start here": "先看这里",
        "Money logic": "资金逻辑",
        "Tools": "工具",
        "Personalization & privacy": "个性化与隐私",
        "Tap to show answer": "点按显示回答",
        "Tap to hide answer": "点按收起回答",
        "help_balance": "快速查看本月资金进出。",
        "help_safe_daily": "扣除账单、目标和计划支出后的余额。",
        "How Safe to Spend is calculated": "可安全支出的计算方式",
        "help_safe_to_spend_logic": "从每月资金中扣除账单、目标、债务和计划支出。",
        "Transfers and credit cards": "转账和信用卡",
        "help_transfers_credit_cards": "账户转账和信用卡还款不算支出。",
        "Refunds and reimbursements": "退款和报销",
        "help_refunds_reimbursements": "退款会尽量抵扣原来的购买。",
        "Review suggestions": "待确认建议",
        "help_review_suggestions": "不确定的项目会先请您确认。",
        "Watchlists": "关注列表",
        "help_watchlists": "关注咖啡、外食、Amazon 等项目。",
        "help_categories": "查看本月钱花在哪里。",
        "AI Analysis": "AI分析",
        "Savings goals": "储蓄目标",
        "Local data only": "仅本地数据",
        "help_goals": "查看目标进度，并快速存入金额。",
        "help_ai": "生成简短支出摘要。在线 AI 太慢时，会改用本机摘要。",
        "help_subscriptions": "手动添加、App Store 扫描、候选确认都可以。",
        "help_wallpaper": "把照片、颜色和外观保存成配置。",
        "help_local_privacy": "无需银行登录。数据留在本机。",
        "Welcome to PennyLet": "欢迎使用PennyLet",
        "Track your spending, build healthy budgets, and reach your financial goals.": "追踪支出，建立健康预算，实现财务目标。",
        "Back": "返回",
        "Next": "下一步",
        "Get Started": "开始使用",
        "Please enter a valid monthly income": "请输入有效的月收入",
        "Preferences": "偏好设置",
        "Appearance": "外观",
        "Preset themes": "预设主题",
        "Custom color": "自定义颜色",
        "Visible Blocks": "显示模块",
        "Reset Visible Blocks": "重置显示模块",
        "Color Mode": "颜色模式",
        "Font": "字体",
        "Wallpaper Theme": "壁纸主题",
        "Wallpaper": "壁纸",
        "PennyLet reads the main colors from your wallpaper and tints the app automatically.": "PennyLet 会读取壁纸的主要颜色，并自动调整应用配色。",
        "Import Wallpaper": "导入壁纸",
        "Change Wallpaper": "更换壁纸",
        "Remove Wallpaper Theme": "移除壁纸主题",
        "Analyzing wallpaper colors...": "正在分析壁纸颜色...",
        "Wallpaper colors active": "壁纸配色已启用",
        "Wallpaper color themes": "壁纸配色主题",
        "Card box color themes": "卡片配色主题",
        "Use wallpaper colors": "使用壁纸配色",
        "Use accent color": "使用强调色",
        "Use background color": "使用背景色",
        "Delete Wallpaper Theme": "删除壁纸主题",
        "Delete Wallpaper Theme?": "删除壁纸主题？",
        "Only this saved wallpaper theme will be deleted.": "只会删除这个已保存的壁纸主题。",
        "Saved Wallpaper Profiles": "已保存的壁纸配置",
        "Save Profile": "保存配置",
        "Name Profile": "配置名称",
        "Profile name": "配置名称",
        "Save the current wallpaper, crop, and appearance settings as a profile.": "将当前壁纸、裁剪和外观设置保存为配置。",
        "Profile saved": "配置已保存",
        "Crop Current Wallpaper": "重新裁剪当前壁纸",
        "Crop Wallpaper": "裁剪壁纸",
        "Use Crop": "使用裁剪",
        "Pinch and drag to frame your wallpaper.": "双指缩放并拖动来调整壁纸构图。",
        "Wallpaper theme is active. Remove it to use manual colors.": "壁纸主题已启用。移除后才能使用手动颜色。",
        "Wallpaper visibility": "壁纸显示强度",
        "Wallpaper blur": "壁纸模糊",
        "Card opacity": "卡片不透明度",
        "Wallpaper frame": "壁纸构图",
        "Zoom": "缩放",
        "Horizontal frame": "水平位置",
        "Vertical frame": "垂直位置",
        "Could not read that image. Try another wallpaper.": "无法读取这张图片，请尝试其他壁纸。",
        "Region": "地区",
        "Currency": "货币",
        "Your Budget": "您的预算",
        "After tax": "税后",
        "Essential Bills": "固定支出",
        "Rent, utilities, etc.": "房租、水电等",
        "Savings Goal": "储蓄目标",
        "Monthly target": "月度目标",
        "Pay Day": "发薪日",
        "Monthly plan": "月度计划",
        "Monthly income": "月收入",
        "Your usual take-home income for a full month.": "你一个完整月份通常拿到手的收入。",
        "Fixed bills": "固定账单",
        "Rent, utilities, subscriptions, and other must-pay costs.": "房租、水电、订阅等必须支付的费用。",
        "Money to save": "想存下的钱",
        "Amount you want PennyLet to protect each month.": "每个月你希望 PennyLet 帮你保护不花掉的钱。",
        "Pay schedule": "发薪安排",
        "Payday": "发薪日",
        "Choose the day of the month your pay usually arrives.": "选择你通常每月几号发薪。",
        "Choose payday": "选择发薪日",
        "Today snapshot": "今日资金情况",
        "Start from today": "从今天开始",
        "Use today's balance": "使用今天的余额",
        "Use this when you started mid-month. PennyLet only counts money you already have until payday.": "如果你在月中开始使用，打开它。发薪日前 PennyLet 只计算你现在已有的钱。",
        "Today's money": "今天已有的钱",
        "Money available right now before your next payday.": "下次发薪前，你现在可以使用的钱。",
        "Cash": "现金",
        "Physical cash you want counted.": "你想纳入计算的钱包现金等实体现金。",
        "Savings or buffer money PennyLet should not treat as spendable.": "储蓄或缓冲金，不应被 PennyLet 当作可花的钱。",
        "Must-pay costs due before your next paycheck.": "下次发薪前必须支付的费用。",
        "Money you want protected before the next paycheck.": "下次发薪前你想保护不花掉的钱。",
        "Next paycheck": "下一笔工资",
        "Legal": "法律信息",

        // Dashboard
        "Hello, ": "你好，",
        "Summary": "摘要",
        "Favorites": "常用项目",
        "Edit": "编辑",
        "Monthly Income": "月收入",
        "Good morning, ": "早上好，",
        "Good evening, ": "晚上好，",
        "there": "访客",
        "Safe to Spend Today": "今日可安全支出",
        "Safe to Spend": "可安全支出",
        "Daily safe amount": "每日安全金额",
        "After upcoming bills, goals, and planned set-asides.": "已扣除即将到来的账单、目标和计划预留金额。",
        "Daily spending lane": "今日支出范围",
        "Spent": "已支出",
        "Income": "收入",
        "Balance": "余额",
        "Top Categories": "热门类别",
        "This month": "本月",
        "Monthly pulse": "本月概览",
        "Your monthly picture will appear here.": "本月的收支概览会显示在这里。",
        "On track": "进度正常",
        "Over budget": "已超预算",
        "No spending this month": "本月无支出",
        "Recent Activity": "最近交易",
        "View All": "查看全部",
        "No transactions yet": "暂无交易",
        "d left": "天剩余",
        "% used": "%已使用",
        "% of budget used": "预算使用率",

        // Activity
        "Activity": "交易",
        "Search transactions": "搜索交易",
        "Filter": "筛选",
        "Activity Summary": "交易摘要",
        "No Transactions": "暂无交易",
        "No Results": "无结果",
        "Warns you when you're nearing your monthly spending limit.": "当您接近每月支出限额时发出警告。",
        "Sends email alerts to the address below. Requires server setup.": "发送邮件提醒到下方地址。需要服务器设置。",
        "Export CSV": "导出CSV",
        "File name": "文件名",
        "Export": "导出",
        "Auto Analysis Help": "自动分析帮助",
        "Auto Analysis automatically generates daily, weekly, and monthly AI spending insights at your scheduled times. Enable it and set your preferred times below.": "自动分析会在您设定的时间自动生成每日、每周和每月的AI消费洞察。启用后设置首选时间。",
        "Export Successful": "导出成功",
        "File saved as": "文件保存为：",
        "Export & Reset": "导出 & 重置",
        "Export CSV & Reset": "导出CSV并重置",
        "Reset Without Export": "不导出直接重置",
        "Save your data as CSV before resetting? All local data will be cleared.": "重置前是否将数据保存为CSV？所有本地数据将被清除。",
        "Import CSV": "导入CSV",
        "Import Successful": "导入成功",
        "Import Failed": "导入失败",
        "Imported": "已导入",
        "transactions successfully.": "笔交易。",
        "OK": "确定",
        "The file could not be read. Check the format and try again.": "无法读取文件。请检查格式后重试。",
        "Generate Test Data": "生成测试数据",
        "Add your first transaction": "添加第一笔交易",
        "Try a different search": "尝试其他搜索",

        // Goals
        "Goals": "目标",
        "No Goals Yet": "暂无目标",
        "Set savings goals to track your progress": "设定储蓄目标追踪进度",
        "% complete": "%完成",
        "Goal Details": "目标详情",
        "Name": "名称",
        "Target Amount": "目标金额",
        "Current Amount": "当前金额",
        "Frequency": "频率",
        "Weekly": "每周",
        "Biweekly": "每两周",
        "Monthly": "每月",
        "New Goal": "新建目标",
        "Add Goal": "添加目标",
        "Savings direction": "储蓄进度",
        "active goals": "活跃目标",
        "goals": "目标",
        "Delete Goal?": "删除目标？",
        "This cannot be undone.": "此操作无法撤销。",
        "Add money": "添加金额",
        "Goal Quick Add": "目标快捷金额",
        "Quick amount": "快捷金额",
        "Custom amount": "自定义金额",
        "Goal completed!": "目标已完成！",
        "is fully funded.": "已存满。",
        "Money cockpit": "资金驾驶舱",
        "Subscriptions and budget checks live here.": "订阅和预算检查都在这里。",
        "Safe today": "今日可安全使用",
        "Tracked subs": "已追踪订阅",
        "Track recurring charges and renewal dates.": "追踪周期扣款和续费日期。",
        "See pacing, category pressure, and monthly health.": "查看预算进度、分类压力和月度健康度。",

        // Budget Health
        "Budget Health": "预算健康",
        "Budget Overview": "预算概览",
        "Monthly Disposable": "月度可支配",
        "Spending by Category": "分类支出",
        "No spending data this month": "本月无支出数据",
        "Income vs Spending": "收入与支出",
        "Key numbers": "关键数字",
        "Remaining": "剩余",
        "Safe Daily": "日均可花",
        "Days Left": "剩余天数",

        // Upgrade
        "PennyLet Pro": "PennyLet Pro",
        "Free": "免费",
        "Pro": "Pro",
        "Plan": "计划",
        "Yearly (save 40%)": "年度（节省40%）",
        "Processing...": "处理中...",
        "Subscribe": "订阅",
        "Restore Purchases": "恢复购买",
        "More AI Analyses": "更多AI分析",
        "30 daily, 15 weekly, 10 monthly, and 3 forecasts every month": "每月30次每日、15次每周、10次每月、3次预测",
        "Custom Categories": "自定义类别",
        "Create your own spending and income categories": "创建您自己的支出和收入类别",
        "Spending Forecasts": "支出预测",
        "AI predicts next month's spending based on your history": "AI根据您的历史记录预测下月支出",
        "Schedule automatic daily, weekly, and monthly AI analysis": "安排每日、每周和每月的自动AI分析",
        "Forecast": "预测",
        "Spending Forecast": "支出预测",
        "Other": "其他",
        "Weekly Trend": "每周趋势",
        "Next Month": "下月",
        "Monthly Limit Reached": "已达月度上限",
        "Please wait until the first of next month for your usage to refresh.": "请等待下月1日刷新使用次数。",
        "Free Uses Exhausted": "免费使用次数已用完",
        "Upgrade to PennyLet Pro for more analyses and unlimited access.": "升级到PennyLet Pro以获取更多分析和无限访问。",
        " free left of ": "次免费剩余/共",
        " uses this month": "次每月",
        "See AI-predicted spending for next month based on your history.": "查看AI根据您的历史记录预测的下月支出。",
        "New": "新建",
        "New Category": "新类别",
        "Add": "添加",
        "Balance adjustments fix your starting balance. They stay out of spending reports.": "余额调整用于修正起始余额，不会计入支出报表。",
        "Ignore keeps the entry visible but leaves it out of budgets and reports.": "忽略会保留这笔记录，但不计入预算和报表。",
        "Reimbursement is money paid back to you. PennyLet uses it to lower the original cost when possible.": "报销是别人还给你的钱。PennyLet 会尽量用它抵消原本的支出。",
        "/mo": "/月",
        "Upgrade": "升级",
        "Get more AI analyses, visual charts, forecasts, and deeper spending insights.": "获取更多 AI 分析、可视化图表、预测和更深入的消费洞察。",
        "Higher AI limits, forecasts, charts, and automation for heavier tracking.": "为更高频的记录解锁更高 AI 次数、预测、图表和自动分析。",
        "Higher AI limits": "更高 AI 次数",
        "Forecasts": "预测",
        "Charts": "图表",
        "Wallpaper themes": "壁纸主题",
        "Visible block controls": "显示模块控制",
        "Pro unlocks": "Pro 解锁内容",
        "Free vs Pro": "免费版与 Pro",
        "Included": "包含",
        "Richer AI reports": "更详细的 AI 报告",
        "Extra anomaly checks and tailored tips in AI reports": "AI 报告中增加异常检查和个性化建议",
        "Visual Pie Charts": "可视化饼图",
        "Beautiful spending breakdown charts in weekly and monthly reports": "每周和每月报告中精美的消费分类图表",
        "Deeper Spending Insights": "更深入的消费洞察",
        "Detailed patterns, trends, and personalized recommendations": "详细的消费模式、趋势和个性化建议",
        "Just $3.33/month": "每月仅$3.33",
        "AI Spending Insights": "AI消费洞察",
        "Daily, weekly, and monthly analysis": "每日、每周、每月分析",
        "Receipt Scanner": "收据扫描器",
        "Snap receipts to log expenses instantly": "拍照即可即时记录消费",
        "Custom Tags": "自定义标签",
        "Organize transactions your way": "按您的方式整理交易",
        "Budget Alerts": "预算提醒",
        "Get notified when nearing limits": "接近限额时收到通知",
        "Advanced Charts": "高级图表",
        "Deeper insights into your spending": "更深入的消费洞察",
        "Unable to load pricing. Please try again.": "无法加载定价，请重试。",
        "No active subscription found.": "未找到有效订阅。",
        "Purchase restored! Pro features are now unlocked.": "购买已恢复！Pro功能现已解锁。",
        "Pro unlocked! Refreshing...": "Pro已解锁！刷新中...",

        // Receipt Scanner
        "Scan Receipt": "扫描收据",
        "Take Photo": "拍照",
        "Use": "使用",
        "Take a photo of your receipt": "拍摄收据照片",
        "We'll extract the merchant, amount, and category automatically.": "我们将自动提取商家、金额和类别。",
        "Choose Photo": "选择照片",
        "Extracted Details": "提取详情",
        "Review & Edit": "检查与编辑",
        "Tap fields to correct": "点击字段进行修正",
        "Item": "项目",
        "Price": "价格",
        "Total": "合计",
        "Merchant": "商家",
        "Could not load image.": "无法加载图片。",
        "Could not prepare image.": "无法准备图片。",
        "Uploading receipt...": "正在上传收据...",
        "Analyzing with AI...": "AI分析中...",
        "No text found. Try a clearer photo.": "未找到文本。请尝试更清晰的照片。",
        "Extracting details...": "正在提取详情...",
        "Receipt scanning is currently unavailable. Please try again later.": "收据扫描当前不可用。请稍后再试。",
        "Could not parse receipt. Try again.": "无法解析收据，请重试。",

        // Charts / AI
        "Category Breakdown": "类别分布",
        "Daily Spending": "每日支出",
        "Analysis": "分析",
        "PennyLet Intelligence": "PennyLet 智能分析",
        "Practical reads on your spending rhythm.": "用实用方式解读你的支出节奏。",
        "AI History": "AI 历史记录",
        "Money Checks": "用钱检查",
        "Pro learns your rhythm from saved PennyLet data.": "Pro 会从已保存的 PennyLet 数据中学习你的用钱节奏。",
        "Run a quick check when you want a plain-language read.": "想快速看懂时，可以运行一次简单检查。",
        "PennyLet is ready to learn": "PennyLet 已准备好学习",
        "Run a Money Check and Pro will reuse the useful notes across the app.": "运行用钱检查后，Pro 会把有用的提示用到应用其他地方。",
        "Your money math still stays deterministic.": "真实金额仍由固定逻辑计算。",
        "Ask PennyLet": "问 PennyLet",
        "Ask about saved spending, watchlists, subscriptions, or payday.": "可以询问已保存支出、观察项、订阅或发薪日。",
        "What changed this week?": "这周哪里变了？",
        "Pro noticed this": "Pro 注意到",
        "Open Money Checks": "打开用钱检查",
        "Clear saved insights": "清除已保存洞察",
        "Ask about safe spending, subscriptions, watchlists, or what changed.": "可以询问可安心花费、订阅、观察项或哪里变了。",
        "Ask PennyLet is included with Pro.": "问 PennyLet 是 Pro 功能。",
        "No upcoming subscriptions or bills are saved yet.": "还没有保存即将到来的订阅或账单。",
        "in the last 7 days": "最近 7 天",
        "today": "今天",
        "this month": "本月",
        "Learns your rhythm": "学习你的节奏",
        "Checks before payday": "发薪日前提醒",
        "Pro learns your rhythm": "Pro 学习你的节奏",
        "Saved Money Checks help PennyLet explain future changes": "保存的用钱检查会帮助 PennyLet 解释之后的变化",
        "Payday forecasts": "发薪日前预测",
        "Look ahead with saved PennyLet data, not bank login": "用已保存的 PennyLet 数据预测，不需要银行登录",
        "Source-backed Money Checks": "有依据的用钱检查",
        "Every answer stays tied to saved PennyLet data": "每个回答都基于已保存的 PennyLet 数据",
        "Saved insight memory": "已保存洞察记忆",
        "Proactive insight cards": "主动洞察卡片",
        "Richer Money Checks": "更深入的用钱检查",

        // Common labels and settings
        "Language": "语言",
        "Privacy Policy": "隐私政策",
        "Terms of Use (EULA)": "使用条款（EULA）",
        "Category": "类别",
        "Budget": "预算",
        "Rate": "汇率",
        "Converting...": "正在换算...",
        "Could not fetch exchange rate.": "无法获取汇率。",
        "Refresh Exchange Rates": "刷新汇率",
        "Exchange rates updated": "汇率已更新",
        "Date,Type,Category,Amount,Note,Merchant,OriginalCurrency,OriginalAmount,ExchangeRate": "日期,类型,类别,金额,备注,商家,原币种,原金额,汇率",
        "Purchase pending approval.": "购买正在等待批准。",
        "Save 40%": "省 40%",
        "mo": "月",
        "Renews": "续订",
        "monthly": "每月",
        "yearly": "每年",
        "weekly": "每周",
        "daily": "每天",
        "subscription": "订阅",
        "unknown": "未知",

        // AI progress
        "Generate Again": "重新生成",
        "Usage": "使用情况",
        "AI progress": "AI 进度",
        "Current status": "当前状态",
        "Preparing daily insight": "正在准备每日洞察",
        "Building weekly recap": "正在生成每周回顾",
        "Creating monthly insight": "正在生成月度洞察",
        "Forecasting spending": "正在预测支出",
        "Reading your spending data": "正在读取支出数据",
        "Reading local spending data": "正在读取本地支出数据",
        "Preparing AI request": "正在准备 AI 请求",
        "Building local analysis": "正在生成本机分析",
        "AI request sent": "AI 请求已发送",
        "Waiting for AI response": "正在等待 AI 回复",
        "PennyLet waits briefly, then finishes with private local math if needed.": "PennyLet 会短暂等待；如有需要，会用私密本机计算完成结果。",
        "Using local backup summary": "正在使用本机备用摘要",
        "Finishing with a local summary": "正在用本机摘要完成",
        "Your local spending summary is being turned into a readable result.": "正在把本机支出摘要整理成可读结果。",
        "AI response received": "已收到 AI 回复",
        "AI request timed out. Please check your connection and try again.": "AI 请求超时。请检查网络连接后重试。",
        "AI timed out. Try again.": "AI 超时，请重试。",
        "AI service is unavailable. Please try again.": "AI 服务暂时不可用，请稍后重试。",
        "Saving result locally": "正在本地保存结果",
        "Result ready": "结果已准备好",
        "Gathering today's transactions": "正在整理今日交易",
        "Gathering this week's activity": "正在整理本周活动",
        "Gathering this month's activity": "正在整理本月活动",
        "Gathering forecast inputs": "正在整理预测所需数据",
        "Preparing the daily prompt": "正在准备每日分析请求",
        "Preparing the weekly prompt": "正在准备每周回顾请求",
        "Preparing the monthly prompt": "正在准备月度洞察请求",
        "Preparing the forecast prompt": "正在准备预测请求",
        "AI is writing your daily insight": "AI 正在撰写每日洞察",
        "AI is writing your weekly recap": "AI 正在撰写每周回顾",
        "AI is writing your monthly insight": "AI 正在撰写月度洞察",
        "AI is building your spending forecast": "AI 正在生成支出预测",
        "Checking the daily result": "正在检查每日结果",
        "Checking the weekly result": "正在检查每周结果",
        "Checking the monthly result": "正在检查月度结果",
        "Checking the forecast result": "正在检查预测结果",
        "Saving your daily insight": "正在保存每日洞察",
        "Saving your weekly recap": "正在保存每周回顾",
        "Saving your monthly insight": "正在保存月度洞察",
        "Saving your forecast": "正在保存预测",
        "Reviewing local transactions, budgets, goals, categories, and recent activity.": "正在查看本机交易、预算、目标、分类和近期活动。",
        "Turning the relevant spending evidence into a focused AI request.": "正在把相关支出证据整理成清晰的 AI 请求。",
        "Waiting for the AI to return a structured answer. Forecasts can take a little longer.": "正在等待 AI 返回结构化回答。预测可能会稍微久一点。",
        "The online AI is taking too long, so PennyLet is using your on-device spending logic instead.": "在线 AI 响应太慢，PennyLet 正在改用本机支出逻辑生成结果。",
        "Checking the returned text, numbers, and chart data before showing it.": "显示前正在检查返回的文字、数字和图表数据。",
        "Saving the result on this device so it appears in history.": "正在将结果保存在本机，之后会显示在历史记录中。",
        "Your analysis is ready to read.": "分析已经可以阅读。",
        "Finding patterns and outliers": "正在查找模式和异常",
        "Writing tailored advice": "正在撰写个性化建议",
        "Finalizing your result": "正在整理结果",
        "Almost done": "马上完成",
        "Still working": "仍在处理",
        "AI is checking the details": "AI 正在核对细节",
        "Larger histories can take longer": "记录较多时可能需要更久",
        "About": "约",
        "left": "剩余",

        // Help copy
        "This month's income minus expenses. Positive means you're in the green; negative means you're overspending.": "本月收入减去支出。正数表示还有结余，负数表示已经超支。",
        "(Monthly income − essentials − savings goal − already spent) ÷ days remaining. If you spend more than this per day, you'll run out before month-end.": "（月收入 − 固定支出 − 储蓄目标 − 已花金额）÷ 剩余天数。如果每天超过这个金额，月底前预算就会不够。",
        "Your spending this month broken down by category. Instantly see where your money goes.": "按类别查看本月支出，快速了解钱花在了哪里。",
        "AI analyzes your spending patterns and provides daily, weekly, and monthly insights. Free tier includes limited uses.": "AI 会分析你的支出模式，并提供每日、每周和每月洞察。免费版有使用次数限制。",
        "Auto-detects App Store subscriptions on this device and shows monthly and yearly totals.": "自动检测此设备上的 App Store 订阅，并显示月度与年度合计。",

        // Categories
        "Food & Dining": "餐饮",
        "Groceries": "食品杂货",
        "Transport": "交通",
        "Shopping": "购物",
        "Entertainment": "娱乐",
        "Health": "健康",
        "Bills & Utilities": "账单与公用事业",
        "Rent / Housing": "房租与住房",
        "Travel": "旅行",
        "Education": "教育",
        "Gifts": "礼物",
        "Salary": "工资",
        "Freelance": "自由职业",
        "Investment": "投资",
        "Gift": "礼金",

        // Themes and display
        "Light": "浅色",
        "Dark": "深色",
        "System": "跟随系统",
        "Sage": "鼠尾草",
        "Ocean": "海洋",
        "Sunset": "日落",
        "Lavender": "薰衣草",
        "Forest": "森林",
        "Midnight": "午夜",
        "Coral": "珊瑚",
        "Honey": "蜂蜜",
        "Plum": "梅子",
        "Mint": "薄荷",
        "Sky": "天空",
        "Blush": "腮红",
        "Inter": "Inter",
        "Serif": "衬线体",
        "Rounded": "圆体",
        "Mono": "等宽",

        // Shortened product copy
        "Export or delete anytime.": "随时导出或删除。",
        "Start with what you have now. Past data can wait.": "先从现在开始。过去的数据以后再说。",
        "Tell PennyLet what you have now. It helps from here.": "告诉 PennyLet 你现在有什么钱，它就能从这里开始帮你。",
        "No bank login": "无需登录银行",
        "No old cleanup": "不用整理旧账",
        "Explainable local numbers": "可解释的本机数字",
        "Pick a look first. Money setup comes next.": "先选外观，下一步再填金额。",
        "Pick the basics now. You can customize wallpaper later.": "先选基础设置。壁纸以后再细调。",
        "Wallpaper themes live in Settings, so setup stays quick.": "壁纸主题可以在设置里改，这里先快速完成。",
        "Have a CSV? Import it.": "有 CSV？可以导入。",
        "Optional. You can start without old data.": "可跳过。没有旧数据也能开始。",
        "Use what you have right now. Payday does not need to match.": "填现在手上的钱，不需要刚好是发薪日。",
        "Money you can use before payday, like checking.": "发薪日前可用的钱，例如银行卡余额。",
        "Money you do not want to spend.": "不想动用的钱。",
        "PennyLet starts from today.": "PennyLet 从今天开始帮你算。",
        "This connects today to payday.": "连接今天到发薪日之间的空档。",
        "Your usual take-home for a full month.": "一个月通常到手的钱。",
        "Leave blank to use monthly income.": "留空则使用月收入。",
        "Bills due before payday, like rent or subscriptions.": "发薪日前要付的账单，例如房租或订阅。",
        "Money to set aside before payday.": "发薪日前想先留出来的钱。",
        "After payday, PennyLet uses your normal rhythm.": "发薪日后按你的正常节奏继续。",
        "Add a wallpaper now, or do it later.": "可以现在加壁纸，也可以以后再加。",
        "Save this wallpaper as a profile.": "将这张壁纸保存为配置。",
        "New here? Start with Start From Today.": "第一次用？先看“从今天开始”。",
        "Start with what you have. PennyLet explains what is safe.": "从你现在有的钱开始。PennyLet 会解释哪些钱可以安心花。",
        "No old history required": "不需要旧记录",
        "help_no_old_history": "PennyLet 从今天的资金快照就能开始有用。CSV 导入是可选项，不是必需项。",
        "What AI can use": "AI 可以使用什么",
        "help_ai_scope": "AI 只会收到 PennyLet 根据本机已保存数据整理出的摘要。在线 AI 过慢时，PennyLet 会改用本机计算。",
        "When data is missing": "数据不完整时",
        "help_data_gaps": "PennyLet 不会假装缺失的历史记录存在。它会基于已经保存的数据给出结果。",
        "Ready from today": "今天就能开始",
        "Add your first entry when money moves. Past bank history can wait.": "钱有变化时再添加第一笔记录。过去的银行历史可以以后再处理。",
        "Old data optional": "旧数据可选",
        "Local first": "本机优先",
        "Export a CSV first? Reset clears local data.": "先导出 CSV？重置会清除本机数据。",
        "PennyLet pulls colors from your wallpaper.": "PennyLet 会从壁纸提取颜色。",
        "Helps PennyLet stay useful when you start mid-month.": "让月中开始使用也有用。",
        "Private logic for transfers, refunds, recurrings, and reviews.": "本机处理转账、退款、周期项目和待确认内容。",
        "Auto Analysis runs at the times you choose.": "自动分析会在你选择的时间运行。",
        "Pinch and drag to frame it.": "双指缩放并拖动来调整构图。",
        "Checking App Store purchase info iOS allows.": "正在检查 iOS 允许的购买信息。",
        "Apple subscriptions appear here.": "Apple 订阅会显示在这里。",
        "Add non-App Store subscriptions manually.": "App Store 之外的订阅请手动添加。",
        "PennyLet can scan eligible App Store subscriptions.": "PennyLet 可以扫描符合条件的 App Store 订阅。",
        "Uses only purchase info Apple shares with this app.": "只使用 Apple 提供给本应用的购买信息。",
        "Create an account to unlock Pro. Your local setup stays yours.": "创建账户即可解锁 Pro。您的本机设置仍由您掌控。",
        "Your usage refreshes next month.": "使用次数会在下个月刷新。",
        "Upgrade for more AI analyses.": "升级后可使用更多 AI 分析。",
        "Cash you physically have, like money in your wallet.": "钱包等手边实际有的现金。",
        "Money to protect, like emergency savings.": "想保留不花的钱，例如应急金。",
        "Needs attention": "需要注意",
        "Ready": "可使用",
        "Update your balance when money changes.": "钱有变化时，更新一下余额。",
        "Updated today": "今天已更新",
        "Updated": "更新于",
        "Today's money − protected money − bills before payday.": "今天的钱 − 保留的钱 − 发薪日前账单。",
        "Days left": "剩余天数",
        "Quick amounts": "快捷金额",
        "Quick checks": "快速确认",
        "Confirm only what looks right. Ignore the rest.": "只确认看起来正确的项目，其他可以忽略。",
        "Check now": "现在确认",
        "Track one habit without building a full budget.": "不用完整预算，也能关注一个消费习惯。",
        "Games": "游戏",
        "Start with one thing": "先选一个",
        "Set the four amounts that appear on goal cards.": "设置目标卡片上显示的四个快捷金额。",
        "More private reports": "更多私密报告",
        "Auto check-ins": "自动检查",
        "More daily, weekly, monthly, and forecast runs": "更多每日、每周、每月和预测次数",
        "Forecasts from your history": "根据历史预测",
        "Forecasts from your saved history": "根据已保存历史进行预测",
        "Always included": "始终包含",
        "PennyLet never asks for bank credentials.": "PennyLet 永远不会要求你输入银行登录信息。",
        "Old transactions are optional. Today's snapshot is enough to begin.": "旧交易是可选的。今天的资金快照就足够开始。",
        "Explainable numbers": "可解释的数字",
        "Safe to Spend is based on saved local data, bills, goals, and set-asides.": "可安心花费会根据本机已保存数据、账单、目标和预留金额计算。",
        "Source-backed reports": "有依据的报告",
        "Source-backed AI checks": "有依据的 AI 检查",
        "Reports stay tied to saved PennyLet data": "报告会基于已保存的 PennyLet 数据",
        "Local fallback reports": "本机备用报告",
        "A local summary appears if online AI is slow": "在线 AI 过慢时会显示本机摘要",
        "Clear weekly and monthly charts": "清晰的周报和月报图表",
        "Clear weekly and monthly category charts": "清晰的每周和每月分类图表",
        "Your own categories": "自定义分类",
        "Create categories that match your life": "创建符合你生活方式的分类",
        "Scheduled AI check-ins": "定时 AI 检查",
        "Scheduled check-ins without opening the app": "不用打开应用也能定时检查",
        "Smarter checks and tips": "更智能的检查和建议",
        "Reading your local money data.": "正在读取本机数据。",
        "Preparing the AI request.": "正在准备 AI 请求。",
        "Waiting for AI. Forecasts can take longer.": "正在等待 AI。预测可能更久一点。",
        "Waiting briefly for online AI. PennyLet will switch to local math if it takes too long.": "正在短暂等待在线 AI。如果太久，PennyLet 会切换到本机计算。",
        "AI is slow, so PennyLet is using a local summary.": "AI 较慢，PennyLet 正在使用本机摘要。",
        "Checking the result.": "正在检查结果。",
        "Saving on this device.": "正在保存到本机。",
        "Appearance & Wallpaper": "外观与壁纸",
        "Theme, wallpaper, colors, and card opacity.": "设置主题、壁纸、颜色和卡片透明度。",
        "Drag to reorder. Tap plus or check to show or hide.": "拖动可调整顺序。点加号或对勾可显示或隐藏。",
        "Reset Home Layout": "重置首页布局",
        "Hide": "隐藏",
        "Show": "显示",
        "Preparing export...": "正在准备导出...",
        "Preparing your CSV.": "正在生成 CSV。",
        "Delete subscription?": "删除订阅？",
        "Goal deposit shortcut": "目标存钱快捷按钮",
        "Track spending you care about.": "关注你在意的消费。",
        "Watchlists track spending for a merchant or category you care about, like coffee, dining, Amazon, games, or transit.": "关注列表可以追踪你在意的商家或分类，例如咖啡、外食、Amazon、游戏或交通。",
        "Money you can use after bills, goals, and planned costs.": "扣除账单、目标和计划支出后可用的钱。",
        "Money in − money out this month. A quick pulse check.": "本月收入 − 本月支出。快速看一眼资金状态。",
        "Money you have − bills − goals − known costs.": "手上已有的钱 − 账单 − 目标 − 已知支出。",

        // Misc
        "Developer Mode": "开发者模式",
        "Type": "类型",
        "All": "全部",
        "Expense": "支出",
        "Save": "保存",
        "Cancel": "取消",
        "Delete": "删除",
        "Theme": "主题",
        "Saving...": "保存中...",
    ]
}
